### ISSUE TITLE
Add support for DLL build on Windows

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#13]
_From @mloskot on March 19, 2017 0:57_

ATM, building shared library (DLL) on Windows is not really supported: public interfaces are not exported properly so no import library is generated for DLL.

-----

**Request for feedback**: Any Windows users interested in nanodbc as DLL, please speak/thumb up.

-----
Meanwhile, I updated CMake configuration to disable `SHARED` target on Windows (in 83013b3d9483b0db71aa5c089c048a9d962ba9d2, w/ silly mistake corrected in 046f0db1108452411f9690f8b89b0f862ab9ff34).

_Copied from original issue: lexicalunit/nanodbc#246_

**Comment by mloskot** [comment]
No feedback arrived. I assume no one among nanodbc users care about the library as DLL. Closing.
