### ISSUE TITLE
Compiling with MinGW 64 fails

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#14]
_From @bangusi on March 17, 2017 14:16_

Is MinGW supported? I am using this distro of MinGW https://nuwen.net/mingw.html.
Compiling with 
```
NANODBC_USE_UNICODE=on 
NANODBC_DISABLE_ASYNC=off
```

Some of the errors I am getting:
```
nanodbc.cpp: In member function 'void nanodbc::statement::statement_impl::bindtrings(nanodbc::statement::param_direction, short int, const value_type*, std:
ize_t, std::size_t, const bool*, const value_type*)':
nanodbc.cpp:2033:70: error: cannot convert 'const char16_t*' to 'const char*'
r argument '1' to 'int strncmp(const char*, const char*, size_t)'
             if (std::strncmp(s_lhs.c_str(), s_rhs.c_str(), value_size) != 0)
                                                                      ^
main.cpp: In function 'void f0(nanodbc::connection&)':
main.cpp:7:53: error: no matching function for call to 'execute(nanodbc::conneion&, std::__cxx11::wstring&)'
  nanodbc::result results = nanodbc::execute(conn,sql);
```

My sql is like` std::wstring sql = L"select x from some_table"`

_Copied from original issue: lexicalunit/nanodbc#244_

**Comment by lexicalunit** [comment]
_From @mloskot on March 17, 2017 14:23_

We have AppVeyor CI builds configured based on two distributions of MinGW.
Look at details in https://github.com/lexicalunit/nanodbc/blob/master/appveyor.yml

Those builds are configured with `NANODBC_USE_UNICODE=OFF` though.
So, consider the Unicode support not tested with MinGW.

Testing, patches and additional builds configured in `appveyor.yml` would be highly welcome.

**Comment by mloskot** [comment]
No feedback or pull request arrived from @bangusi or others.
I assume MinGW support is not critical.

I don't care about MinGW myself. AFAIU, @lexicalunit does not use it either.

Closing this as wontfix.

PRs are still welcome of course.
