### ISSUE TITLE
Fallback option if SQLDescribeParam is not available?

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#15]
_From @jimhester on March 1, 2017 14:53_

Would it be possible for nanodbc to provide a fallback, possibly by passing parameter sizes manually if a driver does not implement `SQLDescribeParam`?

[freeTDS does not support SQLDescribeParam](http://www.freetds.org/userguide/odbc.api.summary.htm), which means binding parameters with nanodbc fails when using that driver. https://github.com/FreeTDS/freetds/issues/104

_Copied from original issue: lexicalunit/nanodbc#241_

**Comment by lexicalunit** [comment]
_From @AndrewJD79 on March 1, 2017 15:34_

Using SQLDescribeParam also makes stored procedure call two-three times longer for MS SQL driver. It seems it causes an additional round-trip to server.

**Comment by lexicalunit** [comment]
_From @freddy77 on March 1, 2017 15:58_

Yes, the client cannot know the server type and has to ask to the server adding a round-trip.
Which conversion needs to do nanodbc that needs to know the server type?
Or it's just a problem of return parameters?

**Comment by lexicalunit** [comment]
The way I imagine it working is we could have one interface that uses `SQLDescribeParam()` behind the scenes for getting the parameter sizes for auto binding. And another mirror interface that takes the parameter sizes as arguments and just uses them, eliminating the need for `SQLDescribeParam()`. It could probably be written such that the former interface itself calls the later interface. This would require surfacing some private details of the current implementation and refactoring them to be a friendly, consistent, and concise user interface. This new interface would also allow users the opportunity to optimize, for example in MS SQL as @AndrewJD79 mentioned.

This all sounds like **a good idea** to me! Sadly I don't get much time these days to work on this codebase and my role has mostly been to review any PRs that come in and offer whatever advice I may have.

**Comment by lexicalunit** [comment]
_From @mloskot on March 1, 2017 20:24_

Although I can neither offer an opinion nor a solution here, I'll be happy to review any PRs and help with testing any improvements in the pipeline.

@lexicalunit 's idea LGTM

**Comment by mloskot** [comment]
Implemented in https://github.com/nanodbc/nanodbc/pull/225
