### ISSUE TITLE
MS Access cannot select OleDbType.Single (float) values

### ISSUE THREAD

**Issue by MikeStraw** [nanodbc/nanodbc#158]
## Environment

* nanodbc version:  2.12
* DBMS name/version:  MS Access (not sure as to version).
* ODBC connection string:  Driver={Microsoft Access Driver (*.mdb, *.accdb)}
                                            Uid=Admin
                                            Pwd=TeP69s)lAd_mW-(J_72u    <-- yes this is a crazy password
* OS and Compiler:  MS Visual Studio 2015 (C++), pretty much default debug settings (x64)
* CMake settings: just added nanodbc.h/cpp to my project

## Actual behavior
Selecting data from a column of type OleDbType.Single (float) causes an exception.

## Expected  behavior
Should be able to read the value from the DB.

## Minimal Working Example
Basically the following code throws an error during execute() when I include the Fin_Time column. The Fin_Time is contained in an Access column of type OleDbType.Single, which is a 4 byte single precision floating point number. I tried using float, string, int, double but an error was always thrown. If I don't include Fin_Time it works fine. If I use straight ODBC code (ugh!) I can read the Fin_Time column.

	string sql = "Select Ath_no, Pre_heat, Pre_lane, Fin_heat, Fin_lane, Fin_Time"
		         "From Entry where Event_Ptr = " + eventIdStr;
	nanodbc::result sessResult = execute(dbConn, sql);

	while (sessResult.next()) {
		int athleteNo   = sessResult.get<int>(0);
		int preHeat     = sessResult.get<int>(1, 0);
		int preLane     = sessResult.get<int>(2, 0);
		int finHeat     = sessResult.get<int>(3, 0);
		int finLane     = sessResult.get<int>(4, 0);
		float finTime  = sessResult.get<float>(5);
                    ...
             }
I'd be more than happy to submit the Access database file and my code files, if you are interested. I understand that MS Access is a pretty low priority. The data is produced by software that runs swim meets and that software uses MS Access.

Thanks,

Mike Straw
moke.straw AT gmail

**Comment by mloskot** [comment]
@MikeStraw 
> I'd be more than happy to submit the Access database file 

An extract of your database/table would be useful.

> and my code files

No need, assuming the MWE you posted is what is failing for you.

> I understand that MS Access is a pretty low priority

It still may be useful to some/many.

**Comment by MikeStraw** [comment]
Hi Loskot,

Thanks for the reply.  Attached is a ZIP file containing the MS Access 
.mdb file.

The user ID for the Access DB is:   Admin
The password for the Access DB is:  TeP69s)lAd_mW-(J_72u

Let me know if you need anything else.

Mike Straw
mstraw@columbus.rr.com
614-882-7125

P.S.  Another problem with nanodbc and MS Access was basic binding of 
parameters on queries did not work either.  The binding did not work 
even on queries with simple int and char columns.

**Comment by mloskot** [comment]
I'm afraid the attachment did not make it through.
You need to "Attach files by dragging & dropping.." to the comment via GitHub Web - I don't think it works while replying by e-mail.

> Another problem with nanodbc and MS Access was basic binding of parameters on
> queries did not work either.  The binding did not work even on queries
> with simple int and char columns.

Please, open new issue, add MEW, and all that usual business :)

**Comment by MikeStraw** [comment]
[database.zip](https://github.com/nanodbc/nanodbc/files/1749970/database.zip)

**Comment by mloskot** [comment]
I can not reproduce your problem with the current `master` branch at 8402b7cc7e11ab6350c7c6f6a4f2ec7c0ee5f278:

MWE:

```
#include <nanodbc/nanodbc.h>
#include <iostream>

int main()
{
    try
    {
        auto const cs = NANODBC_TEXT(
            "Driver={Microsoft Access Driver "
            "(*.mdb)};Uid=Admin;Pwd=TeP69s)lAd_mW-(J_72u;Dbq=d:\\_\\tmp\\nanodbc\\WC_Gahanna.mdb");
        nanodbc::connection c(cs);
        std::wcout << c.dbms_name() << std::endl;

        nanodbc::string sql = NANODBC_TEXT(
            "Select Ath_no, Pre_heat, Pre_lane, Fin_heat, Fin_lane, Fin_Time "
            "From Entry where Event_Ptr = 35");
        nanodbc::result r = execute(c, sql);
        while (r.next())
        {
            std::cout
                << "\nathleteNo" << "=" << r.get<int>(0)
                << "\tpreHeat" << "=" << r.get<int>(1, 0)
                << "\tpreLane" << "=" << r.get<int>(2, 0)
                << "\tfinHeat" << "=" << r.get<int>(3, 0)
                << "\tfinLane" << "=" << r.get<int>(4, 0)
                << "\tfinTime" << "=" << r.get<float>(5)
                << std::endl;
        }
    }
    catch (std::runtime_error const& e)
    {
        std::cerr << e.what() << std::endl;
    }
}
```

Output:

```
ACCESS

athleteNo=3946  preHeat=0       preLane=0       finHeat=1       finLane=3       finTime=28.05

athleteNo=3952  preHeat=0       preLane=0       finHeat=1       finLane=1       finTime=27.68

athleteNo=3909  preHeat=0       preLane=0       finHeat=1       finLane=4       finTime=26.91

athleteNo=3921  preHeat=0       preLane=0       finHeat=1       finLane=2       finTime=31.69

athleteNo=3924  preHeat=0       preLane=0       finHeat=1       finLane=6       finTime=34.26

athleteNo=3939  preHeat=0       preLane=0       finHeat=1       finLane=5       finTime=27.09
```
