### ISSUE TITLE
truncated results for `varchar(max)` and `nvarchar(max)` fields

### ISSUE THREAD

**Issue by jimhester** [nanodbc/nanodbc#160]
## Environment

* nanodbc version:
* DBMS name/version: SQLServer
* ODBC connection string:
* OS and Compiler: MacOS clang
* CMake settings:

## Actual behavior

nanodbc returns truncated strings for `varchar(max)` and `nvarchar(max)` fields. The particular driver I am using (A proprietary one from Simba) returns `SQL_NO_TOTAL` for `varchar(max)` and `nvarchar(max)` fields. This is a [documented return value](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/using-length-and-indicator-values) for `SQLGetData`, but nanodbc does not currently handle it. This issue surfaced at https://github.com/r-dbi/odbc/issues/156. The below diff (off of the nanodbc version used in that project) fixes the issue by appending the full buffer if this is the value. Looking at the current master it seems the same issue still exists here as well
https://github.com/nanodbc/nanodbc/blob/7f6333749dd253c03ee54fe171ca86990cbcdefc/nanodbc/nanodbc.cpp#L2927-L2934

## Expected  behavior
nanodbc returns full strings for `varchar(max)` and `nvarchar(max)` fields.

## Minimal Working Example

```diff
index 637b0b22..de00b563 100644
--- a/src/nanodbc/nanodbc.cpp
+++ b/src/nanodbc/nanodbc.cpp
@@ -2817,7 +2817,9 @@ inline void result::result_impl::get_ref_impl<string_type>(short column, string_
                     buffer,          // TargetValuePtr
                     buffer_size,     // BufferLength
                     &ValueLenOrInd); // StrLen_or_IndPtr
-                if (ValueLenOrInd > 0)
+                if (ValueLenOrInd == SQL_NO_TOTAL)
+                    out.append(buffer, col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1);
+                else if (ValueLenOrInd > 0)
                     out.append(
                         buffer,
                         std::min<std::size_t>(
@@ -2873,7 +2875,9 @@ inline void result::result_impl::get_ref_impl<string_type>(short column, string_
                     buffer,          // TargetValuePtr
                     buffer_size,     // BufferLength
                     &ValueLenOrInd); // StrLen_or_IndPtr
-                if (ValueLenOrInd > 0)
+                if (ValueLenOrInd == SQL_NO_TOTAL)
+                    out.append(buffer, (buffer_size / sizeof(wide_char_t)) - 1);
+                else if (ValueLenOrInd > 0)
                     out.append(
                         buffer,
                         std::min<std::size_t>(
```

**Comment by mloskot** [comment]
@jimhester Thanks for the report. I've started PR #161 with suggested fix. Next, I'm going to add tests for this issue, if necessary.
