### ISSUE TITLE
TINYINT isn't supported.

### ISSUE THREAD

**Issue by H1X4Dev** [nanodbc/nanodbc#164]
## Environment
* nanodbc version: master
* DBMS name/version: MySQL 8.0
* OS and Compiler: Windows 10 x64, vc140, Windows 8.1 SDK
* CMake settings: not using CMake

## Actual behavior
When compiling you will be given unresolved external symbol linking error when used with a `char` data type alongside `TINYINT` data type for MySQL. All versions are affected the same. To avoid the issue, we are currently forced to use `short` alongside `SMALLINT` instead.

## Expected  behavior
When compiling you should not be given a linking error when used with `char` data type leading availability between MySQL and C/C++ smallest data types.

## Minimal Working Example
```
nanodbc::connection con(L"DSN=test");
nanodbc::statement stmt(con);
stmt.prepare(L"SELECT ?");

char test = 1;
stmt.bind(0, &test);
```

**Comment by mloskot** [comment]
TINYINT is a supported type.
This is however known limitation (see https://github.com/nanodbc/nanodbc/issues/135#issuecomment-358461933). You need to bind short or int.
