### ISSUE TITLE
Need catalog::find_procedures()

### ISSUE THREAD

**Issue by White-Owl** [nanodbc/nanodbc#167]
## Environment

* nanodbc version: 2.12.4
* DBMS name/version: any
* ODBC connection string: n/a
* OS and Compiler: any
* CMake settings: n/a

## Actual behavior
No such function

## Expected  behavior
Similar to catalog::find_tables().
Actually it could be almost copy-paste, but instead of SQLTables() just call SQLProcedures()
https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlprocedures-function

**Comment by mloskot** [comment]
It seems you've figured out how to implement such feature, what prevents you from submitting it as pull request (including a test for it).

**Comment by detule** [comment]
Can probably be closed now.

**Comment by mloskot** [comment]
Implemented by @detule in #249
