### ISSUE TITLE
Reading binary data(BLOB) intermediate termination

### ISSUE THREAD

**Issue by ShreyasNirgude** [nanodbc/nanodbc#171]
## Environment

* nanodbc version: 2.12.4
* DBMS name/version: MySQL 5.7
* IDE-NetBeans 8.2
*Compiler - MingW 7.3
*Package Manger - Msys 2 (64-bit)
*OS - Windows 10 Pro 64 bits

## Actual behavior

After executing the statement " template = row.get<string>(1); " the variable "template" only reads data up-to first NULL character.

## Expected  behavior

The variable "template" should contain entire identification Templete (BLOB) data which is usually 400 bytes long, even if it contains multiple intermediate NULL characters. As identification templete contains binary data it can any value between 0x00 to 0xFF

Code :

```
nanodbc::connection conn("Pro20 ANSI", "root", "root");
    nanodbc::result row = nanodbc::execute(conn, "select * from identification");
    for(int i = 1; row.next(); ++i)
    {
        string          ip, template;
        int64_t         id;
        id = row.get<int64_t>(0);
        ip = row.get<string>(2);
        template = row.get<string>(1);                      //reading BLOB data containing NULL(Image template)
        cout << endl << endl;
    }
```

**Comment by mloskot** [comment]
Please, use the current `master` branch, where those issues have been fixed with updated getters returning binary into `std::vector<std::uint8_t>>`

https://github.com/nanodbc/nanodbc/blob/89b4ca92e0ccd2154c4250cd33d9f2c70d546ec2/nanodbc/nanodbc.cpp#L4949

```
value = row.get<std::vector<uint8_t>>(1)
```

**Comment by ShreyasNirgude** [comment]
Thankyou for resolving the issue.

**Comment by mloskot** [comment]
FYI, implemented as part of this old PR https://github.com/lexicalunit/nanodbc/pull/130
