### ISSUE TITLE
Infinite loop fetching text into buffer

### ISSUE THREAD

**Issue by renkun-ken** [nanodbc/nanodbc#175]
## Environment

* nanodbc version:
* DBMS name/version: SQL Server
* ODBC connection string:
* OS and Compiler: Ubuntu 18.04, g++
* CMake settings:

## Actual behavior

This issue is from https://github.com/r-dbi/odbc/issues/171. Querying specific rows from my table will end up in hanging forever. It turns out that the while loop condition at https://github.com/nanodbc/nanodbc/blob/0f230abfc08e1a6ebe2a5319ebd93129202bb131/nanodbc/nanodbc.cpp#L2939 never violates but each time the buffer is all zeros.

## Expected  behavior

When buffer is filled with all zeros, the while loop should also terminate to avoid some rare case where it never ends.

## Minimal Working Example

In #174, the suggested solution computes `strlen(buffer)` in case of non-`SQL_C_BINARY`. On top of that, if it is zero, then break the loop, as suggested in https://github.com/r-dbi/odbc/pull/190/files#diff-0b9b3e04c00a1b1a48f9188466e2719bR2825.

**Comment by mloskot** [comment]
As commented in https://github.com/r-dbi/odbc/issues/171#issuecomment-396489006 and https://github.com/nanodbc/nanodbc/issues/174#issuecomment-396489711

Limiting size of copied buffer with something between std::min(std::strlen(buffer), buffer_size) sounds like not a bad idea, but wide-characters must be taken into account for SQL_C_WCHAR case.

Pull request **with a test** case is your best bet to get this improved ASAP.

**Comment by renkun-ken** [comment]
Thanks for your suggestion! This is issue is about the infinite loop problem. I'm not sure how this can possibly happen and whether it makes sense to you about the suggested fix (break when `append_size` is zero)?

**Comment by mloskot** [comment]
Right, let's kill the `SQL_C_CHAR` issue first then.
Breaking as soon as there is zero characters to append also sounds fine.

As long as all nanodbc CI builds are green, and PR is not overly complicated, I think nanodbc can accept such _buggy-driver/database-specific_ fixes (my current understanding does not suggest an actual bug in nanodbc)

**Comment by freddy77** [comment]
As far as I know the loop is expected to loop forever in case of non variable fields (like INT).
Do you know when this happens?

**Comment by freddy77** [comment]
One bug of nanodbc code is that rc return value should be checked before using ValueLenOrInd, is not guaranteed that ValueLenOrInd is valid if rc is an error.

**Comment by mloskot** [comment]
@freddy77 You need to be very specific: what nanodbc version, what invocation, which line of code, which `rc`. Finally, if you see a bug, please open new issue and include minimal working example to reproduce it. Thanks

**Comment by renkun-ken** [comment]
Since the upstream is fixed (https://github.com/FreeTDS/freetds/issues/225#issuecomment-426942357), should we revert this when I confirm?

**Comment by mloskot** [comment]
Let's move the discussion to https://github.com/nanodbc/nanodbc/issues/187#issuecomment-427748994
