### ISSUE TITLE
Empty Error message when calling execute

### ISSUE THREAD

**Issue by KrisBMan** [nanodbc/nanodbc#177]
## Environment

* nanodbc version: 2.12.4
* DBMS name/version: ??
* ODBC connection string: Driver={ODBC Driver 17 for SQL Server}; Server=ADDRESS_TO_AWS_ENDPOINT_THAT_WORKS_WITH_TSQL_AND_SQLCMD;Database=kris;Uid=kris;Pwd=password;
* OS and Compiler: 16.04, g++
* CMake settings: Same as sample with NANODBC_ODBC_VERSION = SQL_OV_ODBC3

## Actual behavior
When I run connect on my connection string, everything works fine, but when it calls execute, no errors are thrown, but the line : cpp/nanodbc/nanodbc.cpp:1207:  shows up, and it skips the remainder of my SQL code. That line skips to : 

```
   void open(class connection& conn)
    {
        close();
        RETCODE rc;
        NANODBC_CALL_RC(
            SQLAllocHandle
            , rc
            , SQL_HANDLE_STMT
            , conn.native_dbc_handle()
            , &stmt_);
        open_ = success(rc);
        if(!open_)
            NANODBC_THROW_DATABASE_ERROR(stmt_, SQL_HANDLE_STMT);
        conn_ = conn;
    }
```

So it looks like the connection cannot be opened, and it is throwing an empty error from NANODBC_THROW_DATABASE_ERROR. 

## Expected  behavior
I would expect the library to connect and return the SQL result. 

## Minimal Working Example
```
    std::cout << ("Driver={" + m_DBType + "}; Server=" + m_serverName + ";Database=" + m_DBName +
                  ";Uid=" + m_username + ";Pwd=" + m_password +";") << std::endl;
    try {
        nanodbc::connection m_connection(NANODBC_TEXT(("Driver={" + m_DBType + "}; Server=" + m_serverName + ","
                                                       + std::to_string(m_port) + ";Database=" + m_DBName +
                                                       ";UID=" + m_username + ";PWD=" + m_password +";")));
        m_isConnected = true;
        LOG4CPLUS_DEBUG(m_logger, "Connected to: " + m_serverName + ":" + m_DBName );
        std::cout << "Connected with driver " << (m_connection.driver_name()) << std::endl;

    }
    catch(std::runtime_error e){
        LOG4CPLUS_ERROR(m_logger, "Unable to find driver or create connection to the Database. ");
        m_isConnected = false;
    }

    std::cout << 2 << std::endl;
    nanodbc::execute(m_connection, NANODBC_TEXT("drop table if exists simple_test;"));
    std::cout << 201 << std::endl;
    nanodbc::execute(m_connection, NANODBC_TEXT("create table simple_test (a int, b varchar(10));"));
    std::cout << 202 << std::endl;

    // Accessing results by name, or column number
    nanodbc::result results;
    std::cout << m_query << std::endl;
    std::cout << 21 << std::endl;
    results = nanodbc::execute(m_connection, NANODBC_TEXT("select * from simple_test;"));
    std::cout << 3 << std::endl;

    while(results.next()) {
        std::cout << 4 << std::endl;
        std::cout << std::endl << results.get<int>("first") << ", " << results.get<std::string>(1) << std::endl;
    }
    std::cout << 5 << std::endl;
```

The output from this is: 
```
Driver={ODBC Driver 17 for SQL Server}; Server=ADDRESS_TO_AWS_ENDPOINT_THAT_WORKS_WITH_TSQL_AND_SQLCMD;Database=kris;Uid=kris;Pwd=password;
Connected with driver libmsodbcsql-17.1.so.0.1
2
cpp/nanodbc/nanodbc.cpp:1207: 
```
The program then continues on to do my other work.

My odbc.ini file looks like:
```
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.1.so.0.1
UsageCount=1

[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2
UsageCount=1
```

Any thoughts?
I initially got this all working with straight OBDC, and now cannot get it to work with nanodbc

**Comment by KrisBMan** [comment]
I'm working in C++11, but I now see 2.xx is C++14 .. assuming this will not work then..

**Comment by mloskot** [comment]
First, you did not posted a MWE but a snippet of larger part of some code which is useless if I wanted to re-run it trying to reproduce your problem, trying to help you.

Second, you have a bug in your code
```
try {
        nanodbc::connection m_connection
...
```

The situation you are observing boils down to 
```
connection c;
{
    connection c(connection_string);
} // <--- inner scope connection is destroyed
execute(c, NANODBC_TEXT("SELECT ...")); // // <--- outer scope connection is not open
```

**Comment by KrisBMan** [comment]
as an example, if main from northwind is changed to:

```
int main()
{
    try
    {
        connection conn(NANODBC_TEXT("Driver={ODBC Driver 17 for SQL Server};"
                                     "Server=AWS_PDS_ENDPOINT,1433;"
                                     "Database=kris;Uid=kris;Pwd=password;"));

        std::cout << "Entering Execute" <<std::endl;
        result row = execute(
            conn,
            NANODBC_TEXT("SELECT CustomerID, ContactName, Phone"
                         "   FROM CUSTOMERS"
                         "   ORDER BY 2, 1, 3"));
        std::cout << "Success" <<std::endl;
    }
    catch (runtime_error const& e)
    {
        cerr << e.what() << endl;
    }
    return EXIT_FAILURE;
}

```

Then the output I get is: 
Entering Execute
/nanodbc/nanodbc.cpp:1551: 42S0: [Microsoft][ODBC Driver 13 for SQL Server] 

No errors are thrown, it just silently doesn't work

**Comment by mloskot** [comment]
Are you using the current master branch? If not, please , try the current master branch

**Comment by KrisBMan** [comment]
Most definitely on the current master, up-to-date.
built with cmake flags: NANODBC_ODBC_VERSION = SQL_OV_ODBC3.
Only diff from master is northwind.cpp.

**Comment by mloskot** [comment]
I've never experience such issue.

Possibly, the `rc` below is a non-success code but there is no error state attached to `stmt_` handle:

https://github.com/nanodbc/nanodbc/blob/087a553f36746dcd43b224ac6f5a8296474c8940/nanodbc/nanodbc.cpp#L1550-L1551

I don't see any obvious issue in the nanodbc code reaally.

Perhaps there is something curious happening about the SQL Server at `AWS_PDS_ENDPOINT` or the latest v17 driver on Linux.

I'd suggest to try
* older versions of the driver `{ODBC Driver 13 for SQL Server}`, `{ODBC Driver 13.1 for SQL Server}` or `{ODBC Driver 11 for SQL Server}`.
* driver on Windows, not Linux
* different SQL Server instance (eg. SQL Server Express LocalDB)

There is plenty of bugs in ODBC drivers and I have seen bugs in `{ODBC Driver 13.1 for SQL Server}`, for example.

By the way, you can try to pull & merge locally this PR https://github.com/nanodbc/nanodbc/pull/178/files It should be merged within a few days.

**Comment by KrisBMan** [comment]
Solved it. It was an incorrect query for my database type. Thanks for all the help!
