### ISSUE TITLE
Plan 2.13 release?

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#181]
### Question

@lexicalunit Shall we start planning a new release?

I propose it to be named 2.13 as per #180

### References

I'd like to see all these merged for the next release: #147, #151, #178, #180

**Comment by lexicalunit** [comment]
Yep, semver demands that it be 2.13 if we're adding features, such as #147. If we break any existing APIs we should move to 3.0. I don't think we will though.

**Comment by slowexit** [comment]
When is 2.13 expected to be released?

**Comment by mloskot** [comment]
@lexicalunit I think we should issue 2.13 based on the current master. I think it's ready to go public  :)

**Comment by lexicalunit** [comment]
Agreed!

**Comment by mloskot** [comment]
I have collected release notes for v2.13
https://github.com/nanodbc/nanodbc/commit/2de3cfc955051321cc7d0913b13f53a41edfb4c5

**Comment by lexicalunit** [comment]
I think so yeah 👍

**Comment by mloskot** [comment]
The new release is out: https://github.com/nanodbc/nanodbc/releases/tag/v2.13.0

The new documentation for the latest version: https://nanodbc.github.io/nanodbc/

The old documentation for the previous version: https://nanodbc.github.io/nanodbc/v2.12.4/
