### ISSUE TITLE
Add has_affected_rows method to result class

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#182]
The `result::affected_rows()` returns `0` or larger number, if number of affected rows is available (eg. implemented/provided by a driver).
Otherwise, it returns `-1` to signal number of affected rows is not available.

This is correct and expected behaviour, but the interface could be improved by adding `result::has_affected_rows()` with the following semantic:

```
nanodbc::result r = ...;
assert(r.has_affected_rows() == (r.affected_rows() >= 0));
```

This trivial addition would make the interface similar to C++ standard containers' with `C::size()` and `C::empty()`.

Obvious benefit is that users no longer have to remember which operator to use and what return value to test" `r.affected_rows() > 0` or `r.affected_rows() > -1` or `!(r.affected_rows() <=0)`, etc

@lexicalunit Thoughts? Objections?

**Comment by lexicalunit** [comment]
Definitely seems like it'd be a good addition to the API 👍
