### ISSUE TITLE
Add public macro NANODBC_THROW_NO_SOURCE_LOCATION

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#183]
## Actual behavior

`NANODBC_THROW_DATABASE_ERROR` always throws exception with message containing source code locations. It would be useful if users are able to control this.

## Expected  behavior

Add public macro `NANODBC_THROW_NO_SOURCE_LOCATION` to disable the default behaviour

```
#ifdef NANODBC_THROW_NO_SOURCE_LOCATION
#define NANODBC_THROW_DATABASE_ERROR(handle, handle_type)                                          \
    throw nanodbc::database_error(                                                                 \
        handle, handle_type, "ODBC database error: ") /**/
#else
#define NANODBC_THROW_DATABASE_ERROR(handle, handle_type)                                          \
    throw nanodbc::database_error(                                                                 \
        handle, handle_type, __FILE__ ":" NANODBC_STRINGIZE(__LINE__) ": ") /**/
#endif
```

## Related proposal

Add `NANODBC_THROW_<exception>_ERROR` macros per exception class, so they can also use the mechanism reporting the source code location.

All the throwing macros would be controlled via `NANODBC_THROW_NO_SOURCE_LOCATION`.

@lexicalunit Thoughts?

**Comment by lexicalunit** [comment]
That does seem like it would be nice to have especially for release builds for example.
