### ISSUE TITLE
Do not strlen to work around FreeTDS bug

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#187]
From https://github.com/nanodbc/nanodbc/issues/174#issuecomment-410460723

> Sorry to add a comment to a closed bug but I got confused by all these issues, not sure if I should comment this one, #171, #176 or whatever.
> I'm maintaining FreeTDS software. This is a bug in FreeTDS, nanodbc should not use strlen to avoid the bug in this specific driver but FreeTDS should be fixed and nanodbc should refer to the fixed version. In theory some database could implement string with NUL bytes (not as terminator) support and using strlen could lead to performance regressions.

# References 

- #174
- #176

**Comment by renkun-ken** [comment]
Since FreeTDS has fixed https://github.com/FreeTDS/freetds/issues/224 and https://github.com/FreeTDS/freetds/issues/225. Should we revert the changes I've done to walk-around?

**Comment by mloskot** [comment]
Replying to the above and https://github.com/nanodbc/nanodbc/issues/175#issuecomment-427616589 here:

First, we are talking about reverting the change merged from #176 
I'm trying to think of a situation if this `std::strlen(buffer)` can hurt in any way. 
I see two choices:

- Revert and forget
- Keep assuming it is benign and does not hurt any functionality or performance

**Comment by freddy77** [comment]
Beside performances the question is: Is there any multi-byte encoding where a 0 byte can be part of a character? In this case stripping ending zeroes can lead to string corruptions.
Not mentioning that if the user wants to embed NUL characters into strings this strlen will strip valid characters.
Maybe would be helpful also to check for FreeTDS version after connection and give a warning if the a buggy version is detected.

**Comment by mloskot** [comment]
>  Is there any multi-byte encoding where a 0 byte can be part of a character? 

For multibyte character strings a general rule is to assume there is:

> A multibyte character string is layout-compatible with null-terminated byte string (NTBS), that is,
> can be stored, copied, and examined using the same facilities,
> **except for calculating the number of characters**. - https://en.cppreference.com/w/c/string/multibyte


Extending the options:

1. Revert the change (I'm not very supportive to pollute the code with FreeTDS  version detection).
2. Keep but convert the `buffer` to `std::wstring` to obtain the correct `wcslen`-based size.

Shall we go for No. 1?  /cc @lexicalunit

**Comment by mloskot** [comment]
Please, review the reverting PR #198

**Comment by mloskot** [comment]
@lexicalunit and others, since we've all agreed here that reverting is the right way to do, I've just merged #198 into the master branch.
