### ISSUE TITLE
TIME / TIMESTAMP with timezone and fractional seconds

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#19]
_From @mloskot on November 16, 2016 17:13_

* SQL Server has `DateTimeOffset` SQL type (ODBC slang: `SQL_SS_TIMESTAMPOFFSET`) which supports fractional seconds and time zone offset (see [Data Type Support for ODBC Date and Time Improvements](https://msdn.microsoft.com/en-gb/library/bb677267.aspx)).
* PostgreSQL has `time(precision) with time zone` and `timestamp(precision) with time zone` where `precision` indicates fractional seconds.
* MySQL does not store time zone in time types, it recognises fractional seconds but [does not store it](https://dev.mysql.com/doc/refman/5.5/en/datetime.html).
* I'm not sure about other popular databases.

I'd like to propose small update to `nanodbc::time` 

```
struct time
{
    std::int16_t hour; ///< Hours since midnight [0-23].
    std::int16_t min;  ///< Minutes after the hour [0-59].
    std::int16_t sec;  ///< Seconds after the minute.
    std::int16_t fract;///< Fractional second digits.
}
```

and  `nanodbc::timestamp`

```
struct timestamp
{
    std::int16_t year;  ///< Year [0-inf).
    std::int16_t month; ///< Month of the year [1-12].
    std::int16_t day;   ///< Day of the month [1-31].
    std::int16_t hour;  ///< Hours since midnight [0-23].
    std::int16_t min;   ///< Minutes after the hour [0-59].
    std::int16_t sec;   ///< Seconds after the minute.
    std::int32_t fract; ///< Fractional seconds.
    std::int32_t timezone_hour; ///< Timezone hour offset (negative or positive).
    std::int32_t timezone_min;  ///< Timezone minutes offset (sign as timezone_hour).
};
```

to support fractional seconds and time zone offset.

What do you think about such changes?

_Copied from original issue: lexicalunit/nanodbc#224_

**Comment by lexicalunit** [comment]
I've very much for this! When I first created the `time` and `timestamp` structs I didn't have a good use-case for them because I personally was not actually using them in my code. So I have never felt entirely confident that the structures as-is are sufficient for the needs of others. I'm quite sure that timezone, at the very least, will be a very useful addition.

**Comment by lexicalunit** [comment]
_From @mloskot on November 16, 2016 17:33_

I'm glad.

My main use case is around SQL Server, but hopefully those changes will allow to cover PostgreSQL too, and others if necessary.

By the way, despite **SQL Server Native Client (SNAC, SQLNCLI.H) is not supported beyond SQL Server 2012**, the new Microsoft ODBC Driver for SQL Server still reports `TIME` and `DATETIMEOFFSET` SQL types using constants as defined in `SQLNCLI.h` as explained in [Data Type Support for ODBC Date and Time Improvements](https://msdn.microsoft.com/en-gb/library/bb677267.aspx)

```
Time    SQL_SS_TIME2    -154 (SQLNCLI.h)
DatetimeOFFSET  SQL_SS_TIMESTAMPOFFSET  -155 (SQLNCLI.h)
```

It's a bit of a mess, but we may need to accommodate some changes for `SQL_SS_TIME2` and `SQL_SS_TIMESTAMPOFFSET` too. I'm going to check what constants report pgsqlODBC and others which support similar types.

**Comment by lexicalunit** [comment]
_From @mloskot on November 21, 2016 10:18_

My last https://github.com/lexicalunit/nanodbc/issues/224#issuecomment-261014201 turned into a separate issue #226

**Comment by lexicalunit** [comment]
_From @mloskot on November 21, 2016 15:15_

PR #228 adds very minimal support to handle the SQL Server-specific types with existing `nanodbc::timestamp`, without adding any new structures yet. The latter part is still being discussed.

**Comment by lexicalunit** [comment]
_From @mloskot on November 21, 2016 17:5_

Following my findings in #229, extended `nanodbc::time` would not be useful in case of PostgreSQL data types mapping.

I suspect, given the current knowledge, the extended `nanodbc::time|timestamp` structures would be only dedicated to SQL Server-specific uses.  If that is true, perhaps it is better to introduce separate structures and document their uses (or even conditionally-compiled for better clarify, as discussed in https://github.com/lexicalunit/nanodbc/issues/226#issuecomment-261984633).

**Comment by lexicalunit** [comment]
_From @mloskot on November 22, 2016 21:59_

I started thread on pgsqlODBC list: [Binding time and timestamp with time zone data type](https://www.postgresql.org/message-id/CABUeae8fYodDk0jt0NZ1tHChbmWPGj%2BDRYy2805X7dvppWNs7g%40mail.gmail.com)

I also tested and confirmed, what was actually expected, that binding timestamp column as `SQL_C_SS_TIMESTAMPOFFSET` instead of `SQL_C_TIMESTAMP` does not work with the pgsqlODBC driver.

**Comment by mloskot** [comment]
@mkaes I think this one can be closed too by https://github.com/nanodbc/nanodbc/pull/272 ?
