### ISSUE TITLE
Problem with Oracle ODBC Driver 11.1 in Linux

### ISSUE THREAD

**Issue by whizmo** [nanodbc/nanodbc#190]
* nanodbc version: 2.12.4
* DBMS name/version: Oracle 11
* OS and Compiler: Linux Debian 9. GCC.
* CMake settings:
   - NANODBC_USE_BOOST_CONVERT ON
   - The other options are configured as default.

I compiled my application with nanodbc using the unixODBC library.
The Oracle Driver crashes the application with a segmentation fault when connecting to the database.
The isql command was working ok.

The problem was that the Oracle Driver do not support the SQL_LOGIN_TIMEOUT attribute:
https://docs.oracle.com/cd/B28359_01/server.111/b32009/app_odbc.htm#UNXAR372

I solved this by modifying the connect(...) methods of the library:

        if (timeout != 0) {
            // Avoid to set the timeout to 0 (no timeout).
            // This is a workaround for the Oracle ODBC Driver (11.1), as this
            // operation is not supported by the Driver.
            NANODBC_CALL_RC(
                        SQLSetConnectAttr
                        , rc
                        , conn_
                        , SQL_LOGIN_TIMEOUT
                        , (SQLPOINTER)(std::intptr_t)timeout
                        , 0);
            if(!success(rc))
                NANODBC_THROW_DATABASE_ERROR(conn_, SQL_HANDLE_DBC);
        }

**Comment by mloskot** [comment]
Welcome to the 'standardised' world of ODBC ;-)

I think your patch seems reasonable. So, if you could submit a pull request, it would be awesome.
