### ISSUE TITLE
Auto-increment values

### ISSUE THREAD

**Issue by zillemarco** [nanodbc/nanodbc#192]
Sorry to ask this here but I didn't find any other place.
How can nanodbc be used to retrieve the auto-increment value of a column?

**Comment by mloskot** [comment]
Sorry, you have to be specific to make correct sense of your question (any value of any row, last generated value, next value?). So, please explain your use case precisely.

**Comment by mloskot** [comment]
AFAIK, there is no ODBC API to get most recently generated identity value. Since, nanodbc is a _thin_ wrapper on top of the ODBC API, that makes your question ODBC-generic rather than specific to nanodbc features.

To solve your problem, you need to resort to SQL features, database-specific SQL features most likely.

For example, for SQL Server, you can use the [SCOPE_IDENTITY via ODBC](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a8ff34e6-5bb9-494e-a790-2a50cc53abfd/scopeidentity-via-an-odbc-connection?forum=sqldataaccess):

```cpp
auto sql = "INSERT INTO MyTable (data) VALUES ('abc'); SELECT SCOPE_IDENTITY() AS SI";
nanodbc::result r = nanodbc::execute(connection, sql);
assert(r.affected_rows() == 1);
// move to next result set with SCOPE_IDENTITY return value
r.next_result();
// move to first row of the result set
r.next();
// The IDENTITY(seed, increment) return value is NUMERIC(38,0)
// Also, the increment can be negative generating negative values.
// Also, SCOPE_IDENTITY() yields NULL for non-numeric PK
// So, simplify handling by retrieving value via string 
auto si = r.get<nanodbc::string>(0, "");
if (si.empty()) throw ...
auto id = std::stoll(si);
```

**Comment by zillemarco** [comment]
Ok I understand the reason why nanodbc can't provide this feature by default.
Actually I did try something very similar to what you suggest by I missed the `r.next_result()` part so I wasn't getting any row and I thought I was doing something wrong and posted the question here.

Your solution is perfectly working for my case, thank you very much!

**Comment by zillemarco** [comment]
Actually I just found out that one of my collegues achieved the result I was looking for years ago with a different library and it works as well.
It's like this:

```c++
auto sql = "INSERT INTO MyTable (data) OUTPUT INSERTED.ID VALUES ('abc')";
nanodbc::result r = nanodbc::execute(connection, sql);

// r.affected_rows() returns an invalid value (looks like the upper limit of the long type) so we cannot check r.affected_rows() == 1
r.next();
auto si = r.get<nanodbc::string>(0, "");
if (si.empty()) throw ...
auto id = std::stoll(si);
```

**Comment by mloskot** [comment]
This is a good finding indeed.

FWIW, `OUTPUT` clause in `INSERT` is a feature specific to SQL Server, AFAIK, while `INSERT` and `SELECT` bundle processed as multiple result sets may be more generic.

**Comment by zillemarco** [comment]
Yeah, I guess you're right :)
Glad I've been somewhat helpful too :)

**Comment by mloskot** [comment]
I've learned something new as well :)

**Comment by zillemarco** [comment]
One of the nice things of open source :D

**Comment by kitattyor** [comment]
Seems to fail for MySQL when using `last_insert_id()`.

I created the table using:

From client application (using nanodbc) just inserting values work fine.

```
nanodbc::result execute_sql_statement(nanodbc::connection &conn, const std::string &statement)
{
	assert(conn.connected());
	auto res = nanodbc::execute(
		conn,
		statement);
	return res;
}
```

    std::string st = "INSERT INTO arrival (panel_number, pic_start, pic_end) VALUES (888, 10000, 10020);";
    auto res = execute_sql_statement(m_conn, st);

But if I change st to get the last ID inserted, it fails - 

    std::string st = "INSERT INTO arrival (panel_number, pic_start, pic_end) VALUES (888, 10000, 10020); SELECT LAST_INSERT_ID() AS lid;";

I did a bit of digging - 

Seems like 
```
//// nanodbc.cpp
NANODBC_CALL_RC(NANODBC_FUNC(SQLExecDirect), rc, stmt_, (NANODBC_SQLCHAR*)query.c_str(), SQL_NTS);
```
fails with `rc = -1` which triggers the error. 

Any idea how to fix/workaround this issue? 

PS. ```INSERT INTO arrival (panel_number, pic_start, pic_end) VALUES (888, 10000, 10020); SELECT LAST_INSERT_ID() AS lid;``` works from MySQL Workbench.
