### ISSUE TITLE
Using connection in std::map

### ISSUE THREAD

**Issue by Paschover** [nanodbc/nanodbc#195]
Hi.

I was trying to cache connections in an std::map<std::string, std::unique_ptr<connection>>, but I kept having memory leaks. More specifically, this is used in a native C++ Excel add-in, and there is a fairly significant performance penalty if you create a new connection for each SQL query. When I exit Excel, the application seemingly closes, but the process stays alive consuming memory.

I ended up solving the problem by wrapping nanodbc::connection in my own Connection object, which keeps reference counted pointers to nanodbc::connection in a static map. A naive implementation seems to do the trick. But it seems to me that initializing a std::unique_ptr with a pointer to nanodbc::connection should work as well. I don't really have the time to dig through nanodbc.cpp and figure out how to get it to work, but I thought I should mention this.

Thanks,
Marc.

**Comment by bangusi** [comment]
Are you certain the problem is in nanodbc code? I have a more or less similar use case where I store nanodbc connection objects in a std::map but using std::shared_ptr. I haven't experienced any issues so far.
