### ISSUE TITLE
Infinite loop on error: Some character(s) could not be converted into client's character set

### ISSUE THREAD

**Issue by renkun-ken** [nanodbc/nanodbc#197]
Without #176, when FreeTDS fails to convert some characters into client's character set, the text fetching will result in an infinite loop.

See https://github.com/FreeTDS/freetds/issues/239, https://github.com/r-dbi/odbc/issues/171#issuecomment-428484325.

`nanodbc` does not seem to be able to distinguish such error from regular `SQL_SUCCESS_WITH_INFO`, leading to infinite loop. I'm not sure how to reproduce this yet.

With #176 merged, the text is truncated the same way `tsql` returns without an error. This may add info to the discussion at #187.

**Comment by mloskot** [comment]
@renkun-ken Is this still a problem? I see there have been some progress https://github.com/FreeTDS/freetds/issues/239#issuecomment-429502843 
It may be a good idea to add FreeTDS to our CI build jobs.

**Comment by renkun-ken** [comment]
Still not resolved. I'm not sure if it should be handled at freetds side or here?

**Comment by mloskot** [comment]
@renkun-ken That is pity indeed. I'm short of ideas myself. Please, feel free to submit any suggestions you have, that could solve the problem for you. Meanwhile, let's keep this open.

**Comment by mloskot** [comment]
Looks like we've all prematurely agreed on #198 

However, as per https://github.com/nanodbc/nanodbc/issues/174#issuecomment-410460723

> I'm maintaining FreeTDS software. This is a bug in FreeTDS, nanodbc should not use
> `strlen` to avoid the bug in this specific driver but FreeTDS should be fixed and
> nanodbc should refer to the fixed version. 

I'd have expected FreeTDS will fix the bug, and fix it soon.

**Comment by renkun-ken** [comment]
The bug is fixed in FreeTDS. Everything works perfectly for me now.

**Comment by mloskot** [comment]
Great news!
