### ISSUE TITLE
Set connection attributes before connection is made

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#2]
_From @bangusi on September 21, 2017 0:39_

## Environment

_UPDATE: replaced Latest with master ~mloskot_

* nanodbc version: ~~Latest~~ master
* DBMS name/version: SQL Server 2014
* ODBC connection string:
* OS and Compiler: MSVC 2017 ( v 15.3)
* CMake settings:

## Actual behavior
In order to enable bulk copy ( really fast data loads ) using the Microsoft odbc driver you have to enable bcp in the connection attributes. 

My attempt was
```
auto const connection_string = L"Driver={ODBC Driver 13 for SQL Server}; Server=myServer;Database=myDB;Trusted_Connection=Yes";
nanodbc::connection conn(connection_string);
SQLRETURN rc = SQLSetConnectAttr(conn.native_dbc_handle, SQL_COPT_SS_BCP, (SQLPOINTER)SQL_BCP_ON, SQL_IS_INTEGER);
```
## Expected behavior
This does not work. You have to be in bcp mode before you establish the connection.
Here is the documentation and  sample code
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-extensions-bulk-copy-functions/bcp-init

```
 // Allocate ODBC connection handle, set BCP mode, and connect.  
   retcode = SQLAllocHandle(SQL_HANDLE_DBC, henv, &hdbc1);  
   if ( (retcode != SQL_SUCCESS_WITH_INFO) && (retcode != SQL_SUCCESS)) {  
      printf("SQLAllocHandle(hdbc1) Failed\n\n");  
      Cleanup();  
      return(9);  
   }  

   retcode = SQLSetConnectAttr(hdbc1, SQL_COPT_SS_BCP, (void *)SQL_BCP_ON, SQL_IS_INTEGER);  
   if ( (retcode != SQL_SUCCESS_WITH_INFO) && (retcode != SQL_SUCCESS)) {  
      printf("SQLSetConnectAttr(hdbc1) Failed\n\n");  
      Cleanup();  
      return(9);  
   }  

   // Sample uses Integrated Security. Create SQL Server DSN using Windows NT authentication.  
   retcode = SQLConnect(hdbc1, (UCHAR*)"Test", SQL_NTS, (UCHAR*)"", SQL_NTS, (UCHAR*)"", SQL_NTS);  
   if ( (retcode != SQL_SUCCESS) && (retcode != SQL_SUCCESS_WITH_INFO) ) {  
      printf("SQLConnect() Failed\n\n");  
      Cleanup();  
      return(9);  
   }  

   // Initialize the bulk copy.  
   retcode = bcp_init(hdbc1, "BCPDate", "BCPODBC.bcp", NULL, DB_IN);  
   if ( (retcode != SUCCEED) ) {  
      printf("bcp_init(hdbc1) Failed\n\n");  
      Cleanup();  
      return(9);  

```

_Copied from original issue: lexicalunit/nanodbc#292_

**Comment by lexicalunit** [comment]
_From @mloskot on September 21, 2017 7:53_

Currently, it is not possible. The `connection` constructor and `connect()` method allocate and open connection in one go.

New operation will need to be extracted, eg. `connection::allocate()` to allow flow along these lines:

```
connection c1;
SQLSetConnectAttr(c1.native_dbc_handle(), ...);
c1.open(...);
```

By the way, attaching `connection` object to existing handles would be useful too:
```
connection::attach(void* env_handle, void* conn_handle);
```

I've changed this issue to feature request/suggestion.

**Comment by mloskot** [comment]
@bangusi you may want to review PR #147 regarding this features request of yours
