### ISSUE TITLE
OMF lib format need

### ISSUE THREAD

**Issue by durydevelop** [nanodbc/nanodbc#205]
## Environment

* nanodbc version: 2.13.0
* DBMS name/version:
* ODBC connection string:
* OS and Compiler: Windows 10 Builder c++
* CMake settings:

## Actual behavior
Compiled and worked with Microsoft Visual Studio
## Expected  behavior
I need to use it with Builder c++ compiler that needs OMF lib format.
Alreay tried coff2omf tool but in result lib are missing all nanodbc functions.
Is there a possibility to generate a OMF lib?

**Comment by mloskot** [comment]
I have no idea what the OMF is. I can not help.

**Comment by mloskot** [comment]
Closing. This is not related to nanodbc, but to a development environment.
