### ISSUE TITLE
can not build static nanodbc library

### ISSUE THREAD

**Issue by congchp** [nanodbc/nanodbc#208]
## Environment
centos-7.4

* nanodbc version:  
v2.14.2

* CMake settings:
option(NANODBC_STATIC "build static instead of shared library" ON)

Can not build static lib successfully. There are some link errors. I think it is because it does not link boost and odbc libs when build static nanodbc library.

```
########################################
## nanodbc library target
########################################
if(NANODBC_STATIC)
	add_library(nanodbc STATIC src/nanodbc.cpp src/nanodbc.h)
		message(STATUS "Build target: STATIC")
else()
	add_library(nanodbc SHARED src/nanodbc.cpp src/nanodbc.h)
	target_link_libraries(nanodbc ${Boost_LIBRARIES} ${ODBC_LIBRARIES})
	message(STATUS "Build target: SHARED")
endif()
```

**Comment by mloskot** [comment]
Fixed in https://github.com/nanodbc/nanodbc/commit/16bbffda7f651e452e698d5fcb3aab1626075500
