### ISSUE TITLE
XML Causes Unnecessarily Large Memory Allocation

### ISSUE THREAD

**Issue by cjgdev** [nanodbc/nanodbc#213]
## Environment

* nanodbc version: master
* DBMS name/version: SQL Server 2014
* ODBC connection string: DRIVER={SQL SERVER};SERVER=<host>;DATABASE=<db>;
* OS and Compiler: Windows 10, MSVC 2017
* CMake settings: DISABLE_ASYNC=1 ENABLE_BOOST=0 ENABLE_UNICODE=0 ENABLE_WORKAROUND_NODATA=0

## Actual behavior

Executing a statement to query a table with an XML column type causes a very large memory allocation. I have a report that the allocation size is ~2GB.

## Expected  behavior

The data stored in the column is of the order of low single digit kilobytes in size. I would have expected the nanodbc wrapper to allocate just enough memory to store the column data.

## Minimal Working Example

```sql
CREATE TABLE [dbo].[Example](
	[ExampleID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[XMLDef] [xml] NULL)
GO
```

```cpp
nanodbc::statement stmt(*_dbcon);
stmt.prepare(*_dbcon, "SELECT * FROM [dbo].[Example]");
nanodbc::result results = stmt.execute();
while (results.next()) {
    std::string xml = results.get<std::string>(1); // boom
}
```

**Comment by mloskot** [comment]
This reminds similar bug fixed in #211, where
> Binding would attempt to pre-allocate large buffer of size `sizeof(SQLCHAR) * 1073741824`

**Comment by cjgdev** [comment]
Looking at the pull request for #211, shouldn't the case for SQL_NVARCHAR be removed?

```cpp
switch (col.sqltype_)
{
// ... snip ...
case SQL_CHAR:
case SQL_VARCHAR:
case SQL_NVARCHAR: // SQL_NVARCHAR = (-11) - remove?
    col.ctype_ = sql_ctype<std::string>::value;
    col.clen_ = (col.sqlsize_ + 1) * sizeof(SQLCHAR);
    if (is_blob)
    {
        col.clen_ = 0;
        col.blob_ = true;
    }
    break;
// ... snip ...
// #211 START
case SQL_WLONGVARCHAR: // SQL_WLONGVARCHAR = (-11)
    col.ctype_ = sql_ctype<wide_string>::value;
    col.blob_ = true;
    col.clen_ = 0;
    break;
// #211 END
```

**Comment by mloskot** [comment]
See #210

**Comment by cjgdev** [comment]
You were quite right, and does indeed fix the issue. Thank you very kindly for your assistance.

**Comment by mloskot** [comment]
@cjgdev You are welcome.

So, given the current `master` includes the fix from the PRs I linked, the `nanodbc version: master` mentioned in the description was not quite accurate, was it? Or, I'm confused.
