### ISSUE TITLE
Stored Procedure : Exception while attempting to retrive OUT parameter

### ISSUE THREAD

**Issue by IshaanKarnik** [nanodbc/nanodbc#216]
## Environment

* nanodbc version:  2.13.0
* DBMS name/version: MySQL 5.7
* ODBC connection string:
* OS and Compiler: Windows 10 Professional 64-bits, Visual C++ 15.9.11
* CMake settings:

## Actual behavior (Exception)

`[2019-04-22 12:26:24.091] [error] d:\libraries\nanodbc\nanodbc\nanodbc.cpp:1683: HY00: [MySQL][ODBC 8.0(a) Driver][mysqld-5.7.25-log]OUT or INOUT argument 1 for routine seimens_plc_tantrasoft.test_procedure is not a variable or NEW pseudo-variable in BEFORE trigger`

## Expected  behavior

The program should call the stored procedure and return the value 10 which is printed on the console.

## Minimal Working Example
```

#include "pch.h"
#include <array>
#include <iostream>
#include <nanodbc/nanodbc.h>
#include <spdlog/spdlog.h>

#pragma comment(lib, "nanodbc.lib")

int main()
{
	try 
       {
		int result;
		nanodbc::string dns = "PLC_Interface_Tantrasoft";
		nanodbc::string user_name = "root";
		nanodbc::string password = "tantra@123";
		nanodbc::connection conn(dns, user_name, password);
		nanodbc::statement stmt;
		stmt.prepare(conn, "{CALL test_procedure(?)};");
		stmt.bind(0, &result, nanodbc::statement::PARAM_OUT);
		stmt.execute();
		std::cout << result;
		conn.disconnect();
	}
	catch (const std::exception& ex)
	{
		spdlog::error(ex.what());
	}
}
```
## Stored Procedure

```
DROP procedure IF EXISTS `test_procedure`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `test_procedure`(OUT a INT)
BEGIN
	set a = 10;
END$$

DELIMITER ;
```

**Comment by mloskot** [comment]
See example from https://github.com/nanodbc/nanodbc/issues/73#issuecomment-369960053, copied below:

```
uint32_t id{};
nanodbc::connection connection(connectionString);
nanodbc::statement statement(connection);
nanodbc::prepare(statement, L"{CALL test(?)}");
statement.bind(0, &id, nanodbc::statement::PARAM_OUT);
auto result = nanodbc::execute(statement);
// Reading through the results will bind the out parameter
while(result.next_result()) { }
```
