### ISSUE TITLE
Using data source configuration from odbc.ini

### ISSUE THREAD

**Issue by bencz** [nanodbc/nanodbc#218]
Is there any way to just call a connection setup, which is saved inside the "odbc.ini" ?
For example, in my "odbc.ini" I created this setup, how I can call the "odbc:DEV" connection using nanodbc ?:

> [ODBC Data Sources]
> DEV = DEV
> 
> [DEV]
> Description = iSeries Access ODBC Driver
> Driver = IBM i Access ODBC Driver
> System = FQDN or IP
> UserID = USER
> Password = PASSWORD
> Naming = 1
> DefaultLibraries = QGPL
> Database =
> ConnectionType = 2
> CommitMode = 2
> ExtendedDynamic = 1
> DefaultPkgLibrary =
> DefaultPackage = A/DEFAULT(IBM),2,0,1,0,512
> AllowDataCompression = 1
> LibraryView = 0
> AllowUnsupportedChar = 1
> ForceTranslation = 1
> Trace = 0

**Comment by mloskot** [comment]
The `connection` class offers two flavours of `connect` method to 
- either using [SQLDriverConnect](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqldriverconnect-function) from ODBC API.
- or using [SQLConnect](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlconnect-function)

Read the linked documentation pages and learn which one you need (I don't know for sure, presumably the `SQLConnect` one which the data source name (DSN)).

**Comment by bencz** [comment]
@mloskot Thanks!!
I solved the problem:

`nanodbc::connection conn("DEV", "USER", "PASSWORD");`
