### ISSUE TITLE
Broken links on homepage

### ISSUE THREAD

**Issue by supermitch** [nanodbc/nanodbc#222]
## Environment
Links (folder images top right) on homepage (https://nanodbc.github.io/nanodbc/) that supposedly leads to tar.gz (https://codeload.github.com/nanodbc/nanodbc/legacy.tar.gz/release) gives a 404.

Also true for .zip archive.

"See all available releases." link is also spinning endlessly:
(URL: https://nanodbc/nanodbc/releases)

## Actual behavior
Get a 404: `404: Not Found`

## Expected  behavior
Get an archive of newest source.

**Comment by mloskot** [comment]
@supermitch Thanks for the report. I've worked around it in https://github.com/nanodbc/nanodbc/commit/24fed92016d1ad44107981df3c0edb5fc893cec9

FYI, best bet is to use the current `master` branch, which has received lots of fixes and improvements, and is quite ahead of the official release. The `master` is considered stable.
