### ISSUE TITLE
Not able to compile example code

### ISSUE THREAD

**Issue by vikas-29** [nanodbc/nanodbc#223]
hi,

while compiling nanodbc/example/client/nanodbc_client.cpp file in Visual studio 2019 community edition, I am getting below errors.

```
unresolved external symbol "public: __thiscall nanodbc::connection::connection(void)" (??0connection@nanodbc@@QAE@XZ) referenced in function _main	

unresolved external symbol "public: __thiscall nanodbc::connection::~connection(void)" (??1connection@nanodbc@@QAE@XZ) referenced in function __catch$_main$0

unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,
class std::allocator<char> > __thiscall nanodbc::connection::driver_name(void)const " (?driver_name@connection@nanodbc@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function _main	
```

kindly provide a solution

thanks

## Environment

* nanodbc version: v2.12.4
* DBMS name/version: maria db 10.1
* ODBC connection string:
* OS and Compiler: windows 10 and visual c++17
* CMake settings:

## Minimal Working Example
nanodbc/example/client/nanodbc_client.cpp

**Comment by mloskot** [comment]
Those are linker and not compiler errors.

How do you build (not just compile!) the example?

**Comment by vikas-29** [comment]
thanks mloskot for a reply. I thought those are compiler errors. I am using visual studio 2019 community edition, where I copied above example and tried to build the solution. Even I have linked the nanodbc header file as additional include directories.

**Comment by mloskot** [comment]
>  I copied above example and tried to build the solution. Even I have linked the nanodbc header file as additional include directories.

I sense you need to learn how to use VS, create and configure a project, add include directories, add libraries directories, add libraries, etc. Please, refer the Visual Studio configuration.
