### ISSUE TITLE
some error build in centos7

### ISSUE THREAD

**Issue by JZFamily** [nanodbc/nanodbc#226]
## Environment

* nanodbc version:
current
* DBMS name/version:
mysql
* ODBC connection string:
* OS and Compiler:
centos7 gcc4.8.5
* CMake settings:
use unicode
## Actual behavior
1,there are some erorrs. the function SQLColAttribute should be NANODBC_FUNC(SQLColAttribute)
## Minimal Working Example
My english is pool.我的英语很烂， 您能明白大概的意思吗？

**Comment by mloskot** [comment]
> nanodbc version: current

Specifying it as 'current' does not mean much. Is it current `master` branch or current release version?

AFAICT, `SQLColAttribute` is wrapped with the macro in the current `master` branch.

https://github.com/nanodbc/nanodbc/blob/e99606bc8d01257c7c1316dd06f3a9c30e0a71fd/nanodbc/nanodbc.cpp#L2529-L2531

Please, use the current `master` branch, it's received numerous fixes and improvements and it is far ahead from the latest release, it can be considered stable (in fact, it could be released today and it won't be more stable than it is).
