### ISSUE TITLE
Allow out-of-order retrival of unbound columns with SQLGetData without binding

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#228]
TL;TR: This issue discusses how to allow out-of-order retrieval of unbound columns without causing `Invalid Descriptor Index` error due to hitting the [several restrictions on using SQLGetData](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data).

## Problem

Understanding what is the issue is not an easy task and requires diving into the ODBC documentation. Here is minimum of relevant parts extracted:

From https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data

> **There are several restrictions on using SQLGetData.**
>
> Generally, columns accessed with SQLGetData:
> 
> - Must be accessed in order of increasing column number (because of the way the columns of a result set are read from the data source). For example, it is an error to call `SQLGetData for column 5 and then call it for column 4.
> - Cannot be bound.
> - Must have a higher column number than the last bound column. For example, if the last bound column is column 3, it is an error to call `SQLGetData` for column 2. For this reason, applications should make sure to place long data columns at the end of the select list.
> - Cannot be used if `SQLFetch` or `SQLFetchScroll` was called to retrieve more than one row.
> 
> Some drivers do not enforce these restrictions.
> Interoperable applications should either assume they exist or determine which restrictions are not enforced by calling `SQLGetInfo` with the `SQL_GETDATA_EXTENSIONS` option.

From https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-api/sqlgetdata

> SQL Server Native Client ODBC (***) driver does not support using `SQLGetData` to retrieve data in random column order.
> All unbound columns processed with `SQLGetData` must have higher column ordinals than the bound columns in the result set.
> The application must process data from the lowest unbound ordinal column value to the highest.
> Attempting to retrieve data from a lower ordinally numbered column results in an error.

(***) By the way, according to https://github.com/r-dbi/odbc/issues/86#issuecomment-558280484, the SQL Server drivers from FreeTDS, Microsoft ODBC Driver for SQL Server (Windows, MacOS, Linux) do not support the `SQL_GD_ANY_COLUMN` and` SQL_GD_ANY_ORDER`. PostgresSQL, MySQL and SQLite drivers as well as Simba for SQL Server do support those extensions..

## Description

_(This is copy of @jimhester https://github.com/nanodbc/nanodbc/pull/227#issuecomment-558359997)_

So one potential workaround for this issue would be

- check if the driver does not support `SQL_GD_ANY_COLUMN`
- AND there is a long column before non-long columns in the result

Then do not bind any columns after the long column and just use `SQLGetData()` on them directly without binding.

This wouldn't require any reordering / rewriting of the original query. Performance would suffer, but could be rescued if the query was rewritten by the user application or use of drivers which did support `SQL_GD_ANY_COLUMN`.

The main issue I think is that the nanodbc code assumes all columns are bound, so it may take a decent amount of rewriting to support this idea...

## References

- https://github.com/r-dbi/odbc/issues/86
- https://github.com/r-dbi/odbc/issues/309
- Perhaps #20 on simplifying parameters combinations of bind functions could be related to this or could be achieved along of implementing this workaround

**Comment by detule** [comment]
Is one potential way to fix this problem: make the `auto_bind` optional.  Then, a developer who interacts with both `nanodbc` as well as the driver, can opt out of it if they determine, by some means, that the driver does not support the appropriate extensions.  Without any bound columns, (generically, at least) calls to `SQLGetData` would not fail.  Downstream in their code there should be minimal impact (other than the performance hit).

**Comment by krlmlr** [comment]
Slightly related: FreeTDS doesn't seem to want to declare support of `SQL_GD_ANY_COLUMN` (https://github.com/FreeTDS/freetds/issues/335).

**Comment by nickv9** [comment]
This change would essentially result in using SQLGetData() for all columns, right? This seems like a simple approach to me. I see the concerns re: potential performance impact. If code is made available I'd be willing to test in a Windows SQL Server (client and server)) environment. I could benchmark the current vs. new approach and provide the performance data.

**Comment by mloskot** [comment]
I believe we can consider this as fixed via PR #236 Kudos to @detule for the contribution!

**Comment by mloskot** [comment]
> performance hit

I've just posted a little benchmark in the discussion [Performance of bound vs unbound retrieval](https://github.com/nanodbc/nanodbc/discussions/309)
