### ISSUE TITLE
CMake find_program PATHS in the wrong location

### ISSUE THREAD

**Issue by mramthun** [nanodbc/nanodbc#232]
CMakeLists.txt

```
 find_program(ODBC_CONFIG odbc_config
    $ENV{ODBC_PATH}/bin /usr/bin /usr/local/bin PATHS)
```
should be:
```
 find_program(ODBC_CONFIG odbc_config
    PATHS $ENV{ODBC_PATH}/bin /usr/bin /usr/local/bin)
```

In order to link a local libodbc install. As it stands now, with an ODBC_PATH env variable set, it will not find odbc_config.

**Comment by lexicalunit** [comment]
You're totally correct, I just read through [the docs for `find_program`](https://cmake.org/cmake/help/v3.12/command/find_program.html). I'll fix right quick with a PR.

**Comment by mramthun** [comment]
You're the best, thank you.
