### ISSUE TITLE
Binding of parameter in subselect fails

### ISSUE THREAD

**Issue by mkaes** [nanodbc/nanodbc#239]
## Environment
* nanodbc version:
2.13.0
* DBMS name/version:
MSSQL/Express 14

* OS and Compiler:
Windows MSVC2015
* CMake settings:
NANODBC_ENABLE_UNICODE;NANODBC_DISABLE_ASYNC

## Actual behavior
The parameter cannot be bound and a error is thrown:
nanodbc.cpp:1846: 4200: [Microsoft][ODBC SQL Server Driver]Invalid DescriptorIndex  [Microsoft][ODBC SQL Server Driver]Syntax error or access violation
## Expected  behavior
Parameter will be bound a query is executed
## Minimal Working Example

The following code produces the error for me:
`std::string userId;`
`nanodbc::statement statement(m_connection);`
`nanodbc::prepare(statement, NANODBC_TEXT("SELECT ID from [dbo].[test] where ID not in (Select TOP(5) ID from [dbo].[test] where UserId=?)"));`
`statement.bind(0, userId.c_str());`
The bind will throw an exception that the descriptor index is invalid.
The table for this is example is simply
`create table [dbo].[test](
	ID int PRIMARY KEY,
	UserId varchar(20)
)`

**Comment by mloskot** [comment]
Not able to reproduce

```cpp
#include <nanodbc/nanodbc.h>
#include <iostream>

int main()
{
    try
    {
        nanodbc::connection c(NANODBC_TEXT("driver={ODBC Driver 17 for SQL Server};server=localhost;database=nanodbc;uid=sa;pwd=C@dcorp123"));
        
        nanodbc::string userId = NANODBC_TEXT("u1");
        nanodbc::statement s(c);
        nanodbc::prepare(s, NANODBC_TEXT("SELECT ID, UserId from [dbo].[test] where ID not in (Select TOP(5) ID from [dbo].[test] where UserId=?)"));
        s.bind(0, userId.c_str());

        nanodbc::result r = s.execute();
        while (r.next())
        {
            std::wcout
                << NANODBC_TEXT("ID=") << r.get<int>(0)
                << NANODBC_TEXT(", UserId=") << r.get<nanodbc::string>(1)
                << std::endl;
        }

        return EXIT_SUCCESS;
    }
    catch (std::runtime_error const& e)
    {
        std::cerr << e.what() << std::endl;
    }
    return EXIT_FAILURE;
}
```

![image](https://user-images.githubusercontent.com/80741/87811861-98d89300-c85f-11ea-9ddb-676553eb907f.png)

![image](https://user-images.githubusercontent.com/80741/87811995-d50bf380-c85f-11ea-8c18-6395a75c9646.png)

![image](https://user-images.githubusercontent.com/80741/87811972-cc1b2200-c85f-11ea-9ed3-ca3e56ee4b0b.png)

**Comment by mkaes** [comment]
Thanks for the quick reply but the example program does not work in my setup.
It also throws the same exception.

The difference is that I use a system DSN:
`nanodbc::connection c(NANODBC_TEXT("DSN=MyDSN"));`
with the DSN driver being "SQL Server 10.00.28362.01"
I also added 
`c.dbms_name() == 'Microsoft SQL Server'`
`c.dbms_version() == '14.00.2027'`
`c.driver_name() == 'SQLSRV32.DLL'`

and the SQL server is older
`Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64)   Jun 15 2019 00:26:19   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 18363: ) (Hypervisor) `

Could this be a odbc driver issue or is this releated to the SQL server?

**Comment by mloskot** [comment]
You are using an ancient driver, part of MDAC/WDAC components, https://docs.microsoft.com/en-us/sql/connect/connect-history

You should be using the modern driver, the [Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/microsoft-odbc-driver-for-sql-server), which has been available since 2010/2011

> Could this be a odbc driver issue or is this releated to the SQL server?

I'd bet it is.

The older drivers have documented limitations regarding subqueries, for example, the SQL Server Native Client ODBC driver documents [its implementation of SQLDescribeParam](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-api/sqldescribeparam):

> The driver does not support calling SQLDescribeParam in the following situations:
> - For any ODBC or Transact-SQL statement depending on a subquery containing parameters.

The `SQLSRV32.DLL` is even older than `SQLNCLI.DLL`.

I don't think nanodbc is even tested with any of these two old drivers, but the Microsoft ODBC Driver for SQL Server only.

**Comment by mkaes** [comment]
It is indeed the driver.
Using the newer ODBC drivers fixes this issue. So I am closing this one.
Thanks for the help
