### ISSUE TITLE
Cmake package config directory wrong

### ISSUE THREAD

**Issue by gabm** [nanodbc/nanodbc#240]
## Environment

* nanodbc version: master
* DBMS name/version:
* ODBC connection string:
* OS and Compiler: Linux/gcc
* CMake settings:

## Actual behavior

`find_package` doesn't find my library. Thats because the files `nanodbc-config-*.cmake` files are located in `<prefix>/cmake/`. On Linux, this behavior is wrong according to cmake: https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure. It should be `<prefix>/lib/cmake/nanodbc/` or one of the other options mentioned there

## Expected  behavior

`find_package` just finds my package :)

**Comment by gabm** [comment]
I would PR this install folder:

```
  install(EXPORT ${NANODBC_CONFIG} DESTINATION "lib/cmake/${PROJECT_NAME}")
```

Would the community be interested?

**Comment by mloskot** [comment]
Any PR that corrects nanodbc according to the CMake requirements, recommendations or best practices is highly appreciated.

**Comment by gabm** [comment]
I will provide a PR on monday...

**Comment by gabm** [comment]
provided a PR in #243
