### ISSUE TITLE
Asynchronous ODBC Example

### ISSUE THREAD

**Issue by ishaantantra** [nanodbc/nanodbc#258]
I request you to add an example and/or guide for using async_prepare and transaction.
I am developing a cross platform application (Windows and Linux)
I wish to know what should be used in void *event_handle.

**Comment by mloskot** [comment]
Look at the tests as up to date usage examples

https://github.com/nanodbc/nanodbc/blob/11a827ac71016e929345699ac6297e8e64579329/test/mssql_test.cpp#L928-L931
