### ISSUE TITLE
Cmake find_package() can't find nanodbc after install with VCPKG on Linux

### ISSUE THREAD

**Issue by samyy321** [nanodbc/nanodbc#260]
## Environment

* nanodbc version: v2.13.0
* DBMS name/version:
* ODBC connection string:
* OS and Compiler: Linux Ubuntu 20.04
* CMake settings: find_package(nanodbc REQUIRED)

## Actual behavior
On Linux, after VCPKG installation the nanodbc-config*.cmake files are located in `/vcpkg/installed/x64-linux/share/nanodbc/nanodbc/` instead of `/vcpkg/installed/x64-linux/share/nanodbc/` and find_package(nanodbc) can't find them.
CMake error:
```
CMake Error at /tmp/vcpkg/scripts/buildsystems/vcpkg.cmake:331 (_find_package):
  By not providing "Findnanodbc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "nanodbc", but
  CMake did not find one.

  Could not find a package configuration file provided by "nanodbc" with any
  of the following names:

    nanodbcConfig.cmake
    nanodbc-config.cmake
```
It doesn't happen in v2.12.4 or on Windows, maybe it's related to this commit https://github.com/nanodbc/nanodbc/commit/c94f192c6ac71da0fb83fd45a19be51f1a30bb05
## Expected  behavior
After VCPKG installation the nanodbc-config*.cmake files are located in the right location and find_package(nanodbc) don't fail on Linux

## Minimal Working Example
CMakeLists.txt:
```
project("projectName")
find_package(nanodbc CONFIG REQUIRED)
...
```
Install required unixodbc
```
apt update && apt install unixodbc-dev
```

Use a vcpkg containing the v2.13.0 port of nanodbc (vcpkg master branch in that example)
```
git clone https://github.com/Microsoft/vcpkg.git \ 
&& cd vcpkg \
&& ./bootstrap-vcpkg.sh -useSystemBinaries
```
Install nanodbc
```
<pathToVcpkg>/vcpkg install nanodbc
```
Generates the CMake cache.

**Comment by mloskot** [comment]
Isn't it supposed to be handled by vcpkg fixups? See https://github.com/microsoft/vcpkg/pull/13699

**Comment by samyy321** [comment]
I'm on master branch of VCPKG still have the issue.

**Comment by mloskot** [comment]
I understand.
Although I am a vcpkg user and occasional contributor, I'm currently not able to look into this. So, someone has to step out, figure what's going wrong and make a PR, either against vcpkg or nanodbc.

**Comment by samyy321** [comment]
I created a PR on vcpkg side https://github.com/microsoft/vcpkg/pull/16045
