### ISSUE TITLE
Unicode issue in column_datatype_name

### ISSUE THREAD

**Issue by joesiltberg** [nanodbc/nanodbc#262]
## Environment

* nanodbc version: 2.13.0
* DBMS name/version: MS SQL Server
* ODBC connection string: Driver={ODBC Driver 17 for SQL Server};Server=tcp:xxx.database.windows.net,1433;Database=xxx;Uid=xxx;Pwd=xxx;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
* OS and Compiler: Debian Buster, gcc 7.5.0
* CMake settings: NANODBC_ENABLE_UNICODE = ON

## Actual behavior
Column datatype names returned as garbage

## Expected  behavior
Column datatype names returned as utf16 string

The NANODBC_FUNC macro was missing around the call to SQLColAttribute, but the output from the function was treated as utf16 since I had enabled Unicode.

Also the size of the BufferLength sent in to the SQLColAttribute function was incorrectly converted to number of characters, I believe the function expects the length to be in number of bytes.

Will create a PR shortly.

**Comment by mloskot** [comment]
Thanks for the report. I quess, nanodbc vs SQL Server with Unicode support is not extensively tested on Linux.

**Comment by joesiltberg** [comment]
See PR #263 for a suggested fix.
