### ISSUE TITLE
nanodbc::connection is threadsafe ？

### ISSUE THREAD

**Issue by fantasy-peak** [nanodbc/nanodbc#277]

**Comment by mloskot** [comment]
No.

`connection` is just [PIMPL based on `shared_ptr`](https://www.boost.org/doc/libs/1_76_0/libs/smart_ptr/doc/html/smart_ptr.html#techniques_the_pimpl_idiom) with [known thread-safety traits](https://www.boost.org/doc/libs/1_76_0/libs/smart_ptr/doc/html/smart_ptr.html#shared_ptr_thread_safety).

https://github.com/nanodbc/nanodbc/blob/11a827ac71016e929345699ac6297e8e64579329/nanodbc/nanodbc.h#L1208-L1209

**Comment by nqf** [comment]
```
Is it thread safe?
int main() {
    auto db = nanodbc::connection();
    std::thread([]{
      auto result_1 = purple::execute(db, "select * from books where book_auth;");
    }).detach();
    std::thread([]{
      auto result_2 = purple::execute(db, "select * from books where book_auth;");
    }).detach();
}
```

**Comment by mloskot** [comment]
@nqf Is equivalent of your nanodbc sample thread-safe?

```cpp
int main() {
    SQLHANDLE env = ...;
    SQLHANDLE dbc;
    SQLAllocHandle(SQL_HANDLE_DBC, env, &dbc);
    SQLDriverConnect(dbc, 0, "connection string"", SQL_NTS, nullptr, 0, nullptr, SQL_DRIVER_NOPROMPT);

    std::thread([&]{
      SQLHANDLE stmt{nullptr};
      SQLAllocHandle(SQL_HANDLE_STMT, dbc, &stmt);
      SQLExecDirect(stmt, "select * from books where book_auth;", SQL_NTS);
    }).detach();
    std::thread([&]{
      SQLHANDLE stmt{nullptr};
      SQLAllocHandle(SQL_HANDLE_STMT, dbc, &stmt);
      SQLExecDirect(stmt, "select * from books where book_auth;", SQL_NTS);
    }).detach();
}
```

Well, you will need to find out reading about ODBC guarantees and limitations about re-using handles from multiple threads:
- https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/multithreading
- http://www.firstsql.com/ithread5.htm

The nanodbc is just a thin wrapper that makes ODBC API more convenient and less scary and verbose to use.
The nanodbc does NOT offer any custom extra guarantees.
