### ISSUE TITLE
How to use async on Linux/OS X/*nix?

### ISSUE THREAD

**Issue by marty1885** [nanodbc/nanodbc#278]
## Environment

* nanodbc version: master/HEAD
* OS and Compiler: Linux / GCC 11

Hi, the only example I found that uses the async capability is in `mssql_test.cpp`. But that example uses a WIndows only API to create event. Is there a way to use the same async feature on Linux and other UNIX?

**Comment by mloskot** [comment]
> Is there a way to use the same async feature on Linux and other UNIX?

You will have to find out if your ODBC driver manager of your choice does support `SQLSetConnectAttr` with `SQL_ATTR_ASYNC_DBC_EVENT` and what kind of events it expects, to complete these calls made by nanodbc:

https://github.com/nanodbc/nanodbc/blob/20ecbf1f14e9ea96a888f39737206cbb566a68b2/nanodbc/nanodbc.cpp#L910-L921

Microsoft offers sample for Windows
https://docs.microsoft.com/en-us/sql/connect/odbc/windows/asynchronous-execution-notification-method-sample
but they don't seem to offer equivalent for `https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/...`
