### ISSUE TITLE
connected() return always true, even if SQL server service is off.

### ISSUE THREAD

**Issue by madpower2000** [nanodbc/nanodbc#280]
## Environment

* nanodbc version: 2.13.0_x64
* DBMS name/version: MS SQL Server 2016
* ODBC connection string: DSN=SentryPoint;Uid=SentryPoint;Pwd=SentryPoint;
* OS and Compiler: Windows 10, MSVC 2019
* CMake settings: c++17

## Minimal Working Example
```
nanodbc::connection conn(SQLConnectionString); 
try
{
    nanodbc::execute(conn, NANODBC_TEXT(sql.str()));
}
catch (nanodbc::database_error& e)
{
    if (!conn.connected())   
    {              
         conn.connect(SQLConnectionString);
    }
}
```
## Actual behavior
connected() return always true, even if SQL server service is off.

## Expected  behavior

I am developing an app which saves 24x7 some telemetry data to the SQL server database.

If I manually switch off SQL server service during application work, I have got an exception, but conn.connected() returns in the code snippet above  always true instead of false.

How to properly monitor database connection and restore it in case failure?

**Comment by mloskot** [comment]
The MWE above leads to unhandled exception that leads to completely broken world

```cpp
nanodbc::connection conn(SQLConnectionString);  // this throws if server is not reachable
try
{
    nanodbc::execute(conn, NANODBC_TEXT(sql.str())); // if the above throws, this is never executed
}
catch (nanodbc::database_error& e)
{
    // this will never catch any exception from the nanodbc::connection constructor
    if (!conn.connected()) // so this will never execute on connection error
         conn.connect(SQLConnectionString);
}
```

Your example should read something like this:

```cpp
nanodbc::connection conn;
try
{
    conn.connect(SQLConnectionString); // this will throw
    nanodbc::execute(conn, NANODBC_TEXT(sql.str())); // if the above throws, this is never executed
}
catch (nanodbc::database_error& e)
{
    // this will catch the error from the conn.connect above
    if (!conn.connected()) // this will be false, as expected
    {              
         conn.connect(SQLConnectionString);
    }
}
```

**Comment by madpower2000** [comment]
I’m afraid you don't get my point.
I talk about an example where my program executes some SQL commands in an infinity loop, and connection to the server is lost inside this loop.
I assume, nanodbc::execute() throws an exception, because connection is lost and conn.connected() must return false in this case.

**Comment by mloskot** [comment]
Then, IMO, your example is not illustrating your point well. It is missing a critical part, the loop.

- The `nanoodbc::connection` does not continuously poll the connection state to reset itself to disconnected state so `connected() == false`
- The `nanodbc::execute` is a standalone call, it does not modify state of the `conn` object passed to it.
- There is no ODBC-generic/portable technique to monitor connection that I know (if you know one, PR will be very welcome)

So, you will have to resort to driver-specific feature of [SQL_COPT_SS_CONNECTION_DEAD](https://docs.microsoft.com/en-us/sql/connect/odbc/connection-resiliency) etc. to achieve what you need.

**Comment by madpower2000** [comment]
I apologize for the vague code example.
My guess was conn.connected() will probe connection.
Thanks for advice about SQL_COPT_SS_CONNECTION_DEAD , I will try!

**Comment by mloskot** [comment]
nanodbc is a very thin wrapper on top of ODBC API and its calls are usually simple, not offering of any custom complex logic:
https://github.com/nanodbc/nanodbc/blob/70dc808129df3e103641a8f77791e8375c2909ab/nanodbc/nanodbc.cpp#L1053

However, if we know a driver unspecific way to probe connection, then `connection::connected()` can be improved, certainly.
Alternatively, if we can list driver-specific ways to probe connection, then `connection::connected()` could make such checks conditionally (e.g. `if (driver_name() == "XXX") { ... }`. What do you think @lexicalunit ?

Contributions are always welcome!
