### ISSUE TITLE
unable to query redshift 

### ISSUE THREAD

**Issue by omerbrandis** [nanodbc/nanodbc#281]
hello , 

these are my first steps with nano and odbc, so please , be gentle :-)

I've managed to connect to my redshift db/cluster, but not to select data from a table.
( i'm using the current software versions , nano 2.13.0 , redshift odbc 1.4.27.1000-2 , ubuntu 16.04
nano built with -DBUILD_SHARED_LIBS=ON -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3
(btw - I tried using the static lib, failed linkage  )
)

selecting count(*) from a table with 1 row that should return 1 , returns 0 rows.
issued the same select immediatly after , which trows [Amazon][Amazon Redshift] (140) Error occurred while trying to run statement: a statement is already in progress

I't looks like the amazon odbc driver is misused or implemented differently then others,,,but these are my first steps so its a bit hard for me to tell.

**my code:**

```cpp
auto const connstr = NANODBC_TEXT("Driver={..... Database=...; UID=...; PWD=...");
    nanodbc::connection conn;
    try { conn.connect((connstr));}
    catch (const std::exception& e)
    {
        std::cerr << "unable to connect, error text = " <<  e.what() << std::endl;
        return EXIT_FAILURE;
    }

    // execute stmt
    nanodbc::result result;

    try {result = nanodbc::execute(conn, NANODBC_TEXT("SELECT count(*) FROM one_apple;"));}
    catch (const std::exception& e)
    {
        std::cerr << "unable to execute, error text = " <<  e.what() << std::endl;
        return EXIT_FAILURE;
    }

    std::cout << "returned rows " <<  result.rows() << std::endl;

    nanodbc::result result2 = nanodbc::execute(conn, NANODBC_TEXT("SELECT count(*) FROM one_apple;"));
    std::cout << "returned rows " <<  result2.rows() << std::endl;
```

**stdout** 

```
returned rows 0
terminate called after throwing an instance of 'nanodbc::database_error'
  what():  /home/omerbrandis/ffrobotics/nanodbc/nanodbc/nanodbc.cpp:1626: HY01: [Amazon][Amazon Redshift] (140) Error occurred while trying to run statement: a statement is already in progress 
Aborted (core dumped)
```

please advise,
Omer.

**Comment by lexicalunit** [comment]
Just for the future, if you do `` ```cpp `` to start your code block on GitHub you'll get nice syntax highlighting. As far as I can tell the code looks fine to me though. I wonder if maybe Redshift wants you to use transactions or something like that? Sorry I'm not much help here, I've never used Redshift before.

```cpp
nanodbc::connection conn;
auto const connstr = NANODBC_TEXT("Driver={..... Database=...; UID=...; PWD=...");

try {
    conn.connect(connstr);
} catch (const std::exception& e) {
    std::cerr << "unable to connect, error text = " << e.what() << std::endl;
    return EXIT_FAILURE;
}

nanodbc::result result;
auto const querystr = NANODBC_TEXT("SELECT count(*) FROM one_apple;");

try {
    result = nanodbc::execute(conn, querystr);
    std::cout << "returned rows " << result.rows() << std::endl;
} catch (const std::exception& e) {
    std::cerr << "unable to execute, error text = " << e.what() << std::endl;
    return EXIT_FAILURE;
}

result = nanodbc::execute(conn, querystr);
std::cout << "returned rows " << result.rows() << std::endl;
```

**Comment by mloskot** [comment]
@omerbrandis 
> please advise,

You will need to dig and research, hint: [MARS](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view) or similar equivalent and limitations in Redshift
https://stackoverflow.com/questions/28338509/amazon-redshift-is-it-possible-to-return-multiple-result-set
