### ISSUE TITLE
Retrieve view definition from SQL Server fails with Function sequence error

### ISSUE THREAD

**Issue by bangusi** [nanodbc/nanodbc#282]
## Environment

* nanodbc version: v2.13.0
* DBMS SQL Server  14.0.2037.2
* ODBC connection string: Driver={ODBC Driver 17 for SQL Server};server=MyDBServer;database=AdventureWorksDW;trusted_connection=Yes;
* OS and Compiler: Windows 10 ? Visual Studio 2019
NANODBC_DISABLE_ASYNC
NANODBC_ENABLE_UNICODE

* CMake settings:

## Actual behavior
`**nanodbc.cpp:1687: HY01: [Microsoft][ODBC Driver Manager] Function sequence error**`

## Expected  behavior
ddl of dbo.vTargetMail

## Minimal Working Example
```
void f0(nanodbc::connection& connection)
{
    wchar_t sql[]  = L"SELECT definition FROM sys.sql_modules  WHERE object_id = OBJECT_ID('dbo.vTargetMail')";
    nanodbc::statement statement(connection);
    nanodbc::result rs = statement.execute();
    while (rs.next())
    {
        if (!rs.is_null(0))
        {
            auto ddl = rs.get<std::wstring>(0);
            std::wcout << ddl << std::endl;
        }
    }
}
int main()
{
    try
    {
        nanodbc::connection connection;
        std::wstring auth = L"Driver={ODBC Driver 17 for SQL Server};server=MyServer;database=AdventureWorksDW;trusted_connection=Yes;";
        connection.connect(auth.data());
        f0(connection);
    }
    catch (std::runtime_error const& e)
    {
        std::cerr << e.what() << std::endl;
    }
}
```

**Comment by mloskot** [comment]
AFAICT, your example does not execute the `sql` anywhere

**Comment by bangusi** [comment]
You ae absolutely correct.
Should have been
`    wchar_t sql[]  = L"SELECT definition FROM sys.sql_modules  WHERE object_id = OBJECT_ID('dbo.vTargetMail')";
    nanodbc::statement stmt(connection);
    nanodbc::prepare(stmt, sql);
    nanodbc::result rs = stmt.execute();
    while (rs.next())
    {
        if (!rs.is_null(0))
        {
            auto ddl = rs.get<std::wstring>(0);
            std::wcout << ddl << std::endl;
        }
    }`

and behaves as expected.
