### ISSUE TITLE
get SQL type FLOAT as C++ std::string

### ISSUE THREAD

**Issue by pedro-vicente** [nanodbc/nanodbc#288]
## Environment

* nanodbc version: 2.13
* DBMS name/version: SQL server
* ODBC connection string: "Driver={SQL Server};Server=localhost;Database=my_db;"
* OS and Compiler: windows 10, Visual Studio 2022
* CMake settings: 

## Actual behavior

I have a table with a SQL FLOAT type in a column, that for a record was saved to the database as "1.4"
the following program returns that value as std::string = "1"

how can I get the string as the value that was saved , "1.4" ?

## Minimal Working Example

```

include <iostream>
#include <nanodbc/nanodbc.h>

using namespace std;
using namespace nanodbc;

void show(nanodbc::result& results);

int main(int, char*[])
{
    try
    {
        auto const connection_string =
            NANODBC_TEXT("Driver={SQL Server};Server=localhost;Database=my_db;");
        connection conn(connection_string);
        std::cout << conn.dbms_name() << std::endl;

        result result = execute(
            conn, NANODBC_TEXT("SELECT TOP 1 * FROM [my_table] ORDER BY SolId DESC;"));
        show(result);
    }
    catch (std::runtime_error const& e)
    {
        std::cerr << e.what() << std::endl;
    }
}

void show(nanodbc::result& results)
{
    const short columns = results.columns();

    nanodbc::string const null_value = NANODBC_TEXT("NULL");
    while (results.next())
    {
        for (short col = 0; col < columns; ++col)
        {
            cout << results.column_name(col) << " : ";
            std::string value = results.get<nanodbc::string>(col, null_value);
            cout << value << "\n";
        }
        cout << endl;
    }
}

```

**Comment by pedro-vicente** [comment]
this seems like a bug

the column is identified as a SQL_C_DOUBLE instead of a SQL_C_FLOAT
and the number of digits is artificially suppressed

for a number "7.123"
it returns the string "7"



```

case SQL_C_DOUBLE:
    {
        const SQLULEN width = column_size + 2; // account for decimal mark and sign
        std::string buffer(width + 1, 0);      // ensure terminating null
        const double data = *ensure_pdata<double>(column);
        const int bytes = std::snprintf(
            const_cast<char*>(buffer.data()),
            width + 1,
            "%.*lf",    // restrict the number of digits
            col.scale_, // number of digits after the decimal point
            data);
        if (bytes == -1)
            throw type_incompatible_error();
        convert(buffer.data(), result); // passing the C pointer drops trailing nulls
        return;
    }
```

**Comment by pedro-vicente** [comment]
this complete program inserts the float value 

```
#include <iostream>
#include <nanodbc/nanodbc.h>

using namespace std;
using namespace nanodbc;

void show(nanodbc::result& results);

int main(int, char*[])
{
    try
    {
        auto const connection_string =
            NANODBC_TEXT("Driver={SQL Server};Server=localhost;Database=test_db;");
        connection conn(connection_string);
        std::cout << conn.dbms_name() << std::endl;

        execute(conn, "drop table if exists test_table;");
        execute(conn, "create table test_table (a float, b varchar(10));");
        execute(conn, "insert into test_table VALUES (1.4, 'foo');");
        result result = execute(conn, NANODBC_TEXT("SELECT TOP 1 * FROM [test_table];"));
        show(result);
    }
    catch (std::runtime_error const& e)
    {
        std::cerr << e.what() << std::endl;
    }
}

void show(nanodbc::result& results)
{
    const short columns = results.columns();

    nanodbc::string const null_value = NANODBC_TEXT("NULL");
    while (results.next())
    {
        for (short col = 0; col < columns; ++col)
        {
            cout << results.column_name(col) << " : ";
            std::string value = results.get<nanodbc::string>(col, null_value);
            cout << value << "\n";
        }
        cout << endl;
    }
}
```

**Comment by mloskot** [comment]
First, retrieve data using types as close to the SQL types as possible:

```cpp
double value = results.get<double>(col);
```

and then do your desired processing and rounding for displaying purposes.

Obviously nanodbc's `results.get<string>` does its own processing which is based on some arbitrary decisions, better or worse.

> the column is identified as a SQL_C_DOUBLE instead of a SQL_C_FLOAT and the number of digits is artificially suppressed

It's not as simple and as https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-data-types says:

_"[5] Depending on the implementation, the precision of SQL_FLOAT can be either 24 or 53: if it is 24, the SQL_FLOAT data type is the same as SQL_REAL; if it is 53, the SQL_FLOAT data type is the same as SQL_DOUBLE."_

There is number of possible ways to handle it and we did try discuss it a bit https://github.com/nanodbc/nanodbc/issues/82

The auto-binding of `float` to `SQL_C_FLOAT` could be improved though, for example:

```diff
diff --git a/nanodbc/nanodbc.cpp b/nanodbc/nanodbc.cpp
index fb85598..7834ca3 100644
--- a/nanodbc/nanodbc.cpp
+++ b/nanodbc/nanodbc.cpp
@@ -2868,9 +2868,15 @@ private:
                 col.clen_ = sizeof(int64_t);
                 break;
             case SQL_DOUBLE:
+                col.ctype_ = SQL_C_DOUBLE;
+                col.clen_ = sizeof(double);
+                break;
             case SQL_FLOAT:
             case SQL_REAL:
-                col.ctype_ = SQL_C_DOUBLE;
+                // Precision is driver-dependant:
+                // if it is 24, the SQL_FLOAT data type is the same as SQL_REAL;
+                // if it is 53, the SQL_FLOAT data type is the same as SQL_DOUBLE.
+                col.ctype_ = SQL_C_FLOAT;
                 col.clen_ = sizeof(double);
                 break;
             case SQL_DECIMAL:
@@ -3212,10 +3218,10 @@ inline void result::result_impl::get_ref_impl(short column, T& result) const

     case SQL_C_FLOAT:
     {
-        std::string buffer(column_size + 1, 0); // ensure terminating null
+        const SQLULEN width = column_size + 2; // account for decimal mark and sign
+        std::string buffer(width + 1, 0);      // ensure terminating null
         const float data = *ensure_pdata<float>(column);
-        const int bytes =
-            std::snprintf(const_cast<char*>(buffer.data()), column_size + 1, "%f", data);
+        const int bytes = std::snprintf(const_cast<char*>(buffer.data()), width + 1, "%f", data);
         if (bytes == -1)
             throw type_incompatible_error();
         convert(buffer.data(), result); // passing the C pointer drops trailing nulls
```

What do you think @lexicalunit ?

Feel free to submit PRs @pedro-vicente

**Comment by pedro-vicente** [comment]
@mloskot A bit of context on the motivation for the issue.

The goal is to compare some values that were inserted on an existing table with a current insertion of the same value. So, the value is "1.4" and must come out as string "1.4". With this, I know that the value is "correct".

```
create table test_table_3 (a float, b varchar(10));
insert into test_table_3 VALUES (1.4, 'foo');
```

It would be possible to obtain the value as a C float our double type, but that defeats the purpose of the test.
The problem I'm trying to solve is if by means of the ODBC API, if it's possible to achieve this.

I just happened to use nanodbc to get the result, so reported it here.

I did a small ODBC only program that replicates the issue, below.
Output of this program is

`1.3999999999999999 foo`

for the insertion above. This translation was made internally by the ODBC API.

The database is MS SQL server. It would interesting to find out the internal representation that MSSQL does for this insertion of float "1.4". Is the value converted from the string "1.4" in the SQL query to a C float type? In that case, it may or may not be possible to get an accurate same value. But if not, if MSSQL just stores some internal representation of "1.4" "as-is" , then it might be, it they made a public API for that.

Program is

```
#ifdef _MSC_VER
#include <windows.h>
#endif
#include <sql.h>
#include <sqlext.h>
#include <string>
#include <iostream>

struct bind_column_data_t
{
  SQLSMALLINT target_type; //the C data type of the result data
  SQLPOINTER target_value_ptr; //pointer to storage for the data
  SQLINTEGER buf_len; //maximum length of the buffer being bound for data (including null-termination byte for char)
  SQLLEN strlen_or_ind; //number of bytes(excluding the null termination byte for character data) available
  //to return in the buffer prior to calling SQLFetch
};

const std::string conn("Driver={SQL Server};Server=localhost;Database=test_db;");
int exec_direct(SQLHSTMT hstmt, const std::string& sql);
int fetch(SQLHSTMT hstmt, const std::string& sql);

/////////////////////////////////////////////////////////////////////////////////////////////////////
//main
/////////////////////////////////////////////////////////////////////////////////////////////////////

int main()
{
  SQLHENV  henv = SQL_NULL_HENV; //environment
  SQLHDBC  hdbc = SQL_NULL_HDBC; //connection handle
  SQLHSTMT hstmt = SQL_NULL_HSTMT; //statement handle

  std::string sql1 = "drop table if exists test_table_3;";
  std::string sql2 = "create table test_table_3 (a float, b varchar(10));";
  std::string sql3 = "insert into test_table_3 VALUES (1.4, 'foo');";
  std::string sql4 = "select * from[test_table_3];";

  if (!SQL_SUCCEEDED(SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &henv)))
  {
  }
  if (!SQL_SUCCEEDED(SQLSetEnvAttr(henv, SQL_ATTR_ODBC_VERSION, (void*)SQL_OV_ODBC3, 0)))
  {
  }
  if (!SQL_SUCCEEDED(SQLAllocHandle(SQL_HANDLE_DBC, henv, &hdbc)))
  {
  }
  if (!SQL_SUCCEEDED(SQLSetConnectAttr(hdbc, SQL_ATTR_AUTOCOMMIT, (SQLPOINTER)TRUE, 0)))
  {
  }
  if (!SQL_SUCCEEDED(SQLDriverConnect(hdbc, NULL, (SQLCHAR*)conn.c_str(), SQL_NTS, NULL, 0, NULL, SQL_DRIVER_COMPLETE)))
  {
    return -1;
  }
  if (!SQL_SUCCEEDED(SQLAllocHandle(SQL_HANDLE_STMT, hdbc, &hstmt)))
  {
  }

  exec_direct(hstmt, sql1);
  exec_direct(hstmt, sql2);
  exec_direct(hstmt, sql3);
  fetch(hstmt, sql4);

  SQLFreeHandle(SQL_HANDLE_STMT, hstmt);
  SQLDisconnect(hdbc);
  SQLFreeHandle(SQL_HANDLE_DBC, hdbc);
  SQLFreeHandle(SQL_HANDLE_ENV, henv);
  return 0;

  return 0;
}


int exec_direct(SQLHSTMT hstmt, const std::string& sql)
{
  if (!SQL_SUCCEEDED(SQLExecDirect(hstmt, (SQLCHAR*)sql.c_str(), SQL_NTS)))
  {
    return -1;
  }
  return 0;
}

int fetch(SQLHSTMT hstmt, const std::string& sql)
{
  SQLSMALLINT nbr_cols;
  SQLCHAR* sqlstr = (SQLCHAR*)sql.c_str();
  struct bind_column_data_t* bind_data = NULL;

  if (!SQL_SUCCEEDED(SQLExecDirect(hstmt, sqlstr, SQL_NTS)))
  {
    return -1;
  }

  if (!SQL_SUCCEEDED(SQLNumResultCols(hstmt, &nbr_cols)))
  {
  }

  bind_data = (bind_column_data_t*)malloc(nbr_cols * sizeof(bind_column_data_t));
  for (SQLUSMALLINT idx = 0; idx < nbr_cols; idx++)
  {
    bind_data[idx].target_value_ptr = NULL;
  }

  /////////////////////////////////////////////////////////////////////////////////////////////////////
  //get column names
  /////////////////////////////////////////////////////////////////////////////////////////////////////

  for (SQLUSMALLINT idx = 0; idx < nbr_cols; idx++)
  {
    SQLCHAR buf[1024];
    SQLSMALLINT sqltype = 0;
    SQLSMALLINT scale = 0;
    SQLSMALLINT nullable = 0;
    SQLSMALLINT len = 0;
    SQLULEN sqlsize = 0;

    if (!SQL_SUCCEEDED(SQLDescribeCol(
      hstmt,
      idx + 1,
      (SQLCHAR*)buf, //column name
      sizeof(buf) / sizeof(SQLCHAR),
      &len,
      &sqltype,
      &sqlsize,
      &scale,
      &nullable)))
    {
    }
  }

  for (SQLUSMALLINT idx = 0; idx < nbr_cols; idx++)
  {
    bind_data[idx].target_type = SQL_C_CHAR;
    bind_data[idx].buf_len = (1024 + 1);
    bind_data[idx].target_value_ptr = malloc(sizeof(unsigned char) * bind_data[idx].buf_len);
  }

  /////////////////////////////////////////////////////////////////////////////////////////////////////
  //SQLBindCol assigns the storage and data type for a column in a result set,
  //including:
  //a storage buffer that will receive the contents of a column of data
  //the length of the storage buffer
  //a storage location that will receive the actual length of the column of data
  //returned by the fetch operation data type conversion
  /////////////////////////////////////////////////////////////////////////////////////////////////////

  for (SQLUSMALLINT idx = 0; idx < nbr_cols; idx++)
  {
    if (!SQL_SUCCEEDED(SQLBindCol(
      hstmt,
      idx + 1,
      bind_data[idx].target_type,
      bind_data[idx].target_value_ptr,
      bind_data[idx].buf_len,
      &(bind_data[idx].strlen_or_ind))))
    {
    }
  }

  size_t nbr_rows = 0;
  while (SQL_SUCCEEDED(SQLFetch(hstmt)))
  {
    for (int idx_col = 0; idx_col < nbr_cols; idx_col++)
    {
      std::string str;
      if (bind_data[idx_col].strlen_or_ind != SQL_NULL_DATA)
      {
        str = (char*)bind_data[idx_col].target_value_ptr;
      }
      else
      {
        str = "NULL";
      }
      std::cout << str << " ";
    }
    std::cout << "\n";
    nbr_rows++;
  }

  for (SQLUSMALLINT idx_col = 0; idx_col < nbr_cols; idx_col++)
  {
    if (bind_data[idx_col].target_value_ptr != NULL)
    {
      free(bind_data[idx_col].target_value_ptr);
    }
  }
  if (bind_data != NULL)
  {
    free(bind_data);
  }
  SQLFreeHandle(SQL_HANDLE_STMT, hstmt);
  return 0;
}

```

**Comment by pedro-vicente** [comment]
> Feel free to submit PRs @pedro-vicente

Once I solve my original issue, I'll be happy to take a look at your code

**Comment by mloskot** [comment]
> So, the value is "1.4" and must come out as string "1.4". With this, I know that the value is "correct".

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms187912(v=sql.105)

_"Because of the approximate nature of the float and real data types, do not use these data types when exact numeric behavior is required..."_

https://dev.mysql.com/doc/refman/5.7/en/problems-with-float.html

_"Attempts to treat floating-point values as exact in comparisons may lead to problems. They are also subject to platform or implementation dependencies. The [FLOAT](https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html) and [DOUBLE](https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html) data types are subject to these issues."_

Forgive me the metaphor, but you seem to be looking for a holly grail...

**Comment by pedro-vicente** [comment]
@mloskot  Yes, I mentioned that conversion or use to C floating point types is not the solution to the goal 

I found a way for the comparison to work as intended

Because this is for MS SQL Server, it's possible to use the STR function

[](https://docs.microsoft.com/en-us/sql/t-sql/functions/str-transact-sql?view=sql-server-ver15)

function with a length of 3 characters and precision of 1, to match exactly the string "1.4"

```
INSERT INTO test_table_3 VALUES (1.4, 'foo');
SELECT STR(a,3,1), b FROM[test_table_3];
```

Output

`1.4 foo`

**Comment by mloskot** [comment]
@pedro-vicente It 'works' accidentally, but it it's fragile and it will break at some point, https://blog.greglow.com/2018/01/15/sql-newbie-mistake-1-using-float-instead-decimal/
e.g. your `STR` call will receive `1.3999` returning `1.3`

I have no idea what you are trying to achieve, but if it is some sort of a test suite, then no sane test cases compare float-point values exactly.

**Comment by lexicalunit** [comment]
@pedro-vicente I think you're looking for [epsilon comparison](https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon).

When you store a value as a float type using nanodbc you should pull it out as a float type too. String conversion could probably be improved in nanodbc, but even if it was, I don't think you'd want to use it for your use case.

**Comment by pedro-vicente** [comment]
@mloskot 

> I have no idea what you are trying to achieve

There is a database and program code that has this schema and I have to use it because it's already existent

create table test_table_3 (a float, b varchar(10));

I know that someone wrote the value "1.4" in it

insert into test_table_3 VALUES (1.4, 'foo');

I have another program (my program) and I want to insert the same value "1.4" to check if my program is doing the right thing . 

If it returns the result "1.4" , I know that my program retrieves the "same" data as the other program 

I want to know if the 2 programs get the same result

**Comment by mloskot** [comment]
@pedro-vicente 
> I know that someone wrote the value "1.4" in it

The person's assumption is already wrong as it is not necessarily 'written as 1.400000... but 1.399999...

> I want to know if the 2 programs get the same result

IMO, that approach forces the results to _look_ the same, but the results may not be the same.

In any case, I believe there is nothing to do for nanodbc here, so I'm closing this.

If you think there is room of improvement, please feel more than welcome to submit a PR.

@lexicalunit What's your view on this diff I displayed here https://github.com/nanodbc/nanodbc/issues/288#issuecomment-1054072647 ?

**Comment by lexicalunit** [comment]
> @lexicalunit What's your view on this diff I displayed here https://github.com/nanodbc/nanodbc/issues/288#issuecomment-1054072647 ?

Yep, that all makes sense to me. If you make a PR I'll approved it 😉

**Comment by mloskot** [comment]
@lexicalunit I've gone for a different fix, please review https://github.com/nanodbc/nanodbc/pull/295
