### ISSUE TITLE
Result from group_concat is truncated

### ISSUE THREAD

**Issue by raj-blis** [nanodbc/nanodbc#289]
Hello, 

Is there a limit on the size of result from a GROUP_CONCAT call? If so, how can this be configured to have no limit? 

I have an SQLite database, with a simple table - 

`CREATE TABLE test_table(id INT, value VARCHAR(100));`

and has 500 rows, with 'id' ranging from 1 to 500 and 'value' being same for all rows. 

## Minimal Working Example
I run this code -

```
#include <iostream>
#include "nanodbc.h"

int main()
{
   nanodbc::connection connection("Driver=SQLite3;Database=test.db");

   const std::string query =
           "SELECT DISTINCT(value) AS value, GROUP_CONCAT(DISTINCT(id)) AS keys FROM test_table GROUP BY value;";
   nanodbc::result results = nanodbc::execute(connection, query);

   while (results.next())
   {
      std::string output = results.get<std::string>("keys");
      std::cout << "Keys = " << output << std::endl;
   }

   return 0;
}
```
## Expected  behavior
This code should print a list of all 500 comma-separated ids. 

## Actual behavior
The result is a truncated list (255 characters long) of comma-separated ids

## Environment

* nanodbc version: 2.13.0
* DBMS name/version: SQLite3 
* ODBC connection string: Driver=SQLite3;Database=test.db
* OS and Compiler: Ubuntu 18.04, GNU C++17
* CMake settings:

**Comment by mloskot** [comment]
There is an issue with SQLite ODBC driver truncating the value at 255.
The `SQLDescribeCol` reports your `keys` column as `SQL_VARCHAR` (or `SQL_WVARCHAR` which have [size of 255](http://www.ch-werner.de/sqliteodbc/html/sqlite3odbc_8c-source.html):

![image](https://user-images.githubusercontent.com/80741/157007211-d5dc2ed9-7fa2-4371-b893-a5d397533fbd.png)

There is a note in the release notes http://www.ch-werner.de/sqliteodbc/html/index.html saying
> Since May 25th, 2002, SQL_LONGVARCHAR is available but rather experimental. That type is used for SQLite schema containing text or varchar with a size specifier larger than 255.

but I have no idea if this type is enabled by default or not. I'm not a heavy user of the SQLite3 ODBC driver.

There seem to be no bug in the nanodbc as everything works fine using SQL Server, see the equivalent concatenation below.

However, you can workaround the bug in the driver by casting your value to `BLOB`:

```cpp
#include <cassert>
#include <iostream>
#include <list>
#include <string>
#include <nanodbc/nanodbc.h>

int main()
{
    try
    {
        std::list<std::pair<nanodbc::string, nanodbc::string>> connection_and_query =
        {
            {

                "Driver={ODBC Driver 17 for SQL Server};server=localhost;database=nanodbc;uid=sa;pwd=C@dcorp123",
                "SELECT STRING_AGG(v, ',') AS keys FROM t500"
            },
            {

                "Driver={SQLite3 ODBC Driver};Database=d:\\nanodbc\\nanodbc.db",
                "SELECT CAST(GROUP_CONCAT(v) AS BLOB) AS keys FROM t500"
            }
        };

        for (const auto& cq : connection_and_query)
        {
            nanodbc::connection c(cq.first);
            nanodbc::result r = nanodbc::execute(c, cq.second);

            while (r.next())
            {
                auto o = r.get<std::string>("keys");
                assert(o.size() >= 500); // actual size is more than 5900 characters
            }
        }

        return EXIT_SUCCESS;
    }
    catch (std::exception const& e)
    {
        std::cerr << e.what() << std::endl;
    }
    catch (...)
    {
        std::cerr << "unknown error" << std::endl;
    }
    return EXIT_FAILURE;
}
```

The `t500` table in the both databases used in the example above are based on this CSV file [nanodbc.csv](https://github.com/nanodbc/nanodbc/files/8196600/nanodbc.csv).
