### ISSUE TITLE
Rename branch master to main

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#294]
Since "_GitHub is gradually renaming the default branch of our own repositories from `master` to `main`_", see https://github.com/github/renaming, I think it's time to rename it for nanodbc too.

Any objections?

/cc @lexicalunit

**Comment by lexicalunit** [comment]
Yep, seems fine.

**Comment by mloskot** [comment]
Done. Announced at https://github.com/nanodbc/nanodbc/discussions/296
