### ISSUE TITLE
Caching SQL text of prepared statement

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#3]
_From @mloskot on September 20, 2017 15:8_

Currently, once `statement` object has been prepared, that is `SQLPrepare` was called (either via `statement` constructor or explicit `statement::prepare` call later), there is no way to retrieve SQL text of such prepared statement.

ODBC API does not offer any means to do that. There only are database-specific solutions like SQL Servers's `SELECT * FROM sys.dm_exec_sql_text(@sql_handle)`.  See also my SO question [Retrieve SQL text of ODBC prepared statement](https://stackoverflow.com/q/40770725/151641).

---

I think it would be useful to cache the SQL text (eg. for logging, re-creating statements etc.)

I'm thinking about adding private `nanodbc::string query_` to `statement` class accompanied with `nanodbc::query const& query() const` member function.

Any thoughts, better ideas?

_Copied from original issue: lexicalunit/nanodbc#291_

**Comment by lexicalunit** [comment]
_From @bangusi on September 21, 2017 9:41_

This was my exact assumption i.e. the sql  text was a member function of nanodbc::statement until a few days ago. I was getting unrelated sql text in the exception message when I started looking and did not see where the sql was stored. It is possible that was a problem in my code But since you can have only one sql for one statement at a time your proposal makes sense to me.

**Comment by lexicalunit** [comment]
_From @jon-v on September 21, 2017 10:20_

My immediate thought is that automatically storing the SQL text in all prepared statements would do bad things to our application's memory usage (we use a lot of very big queries). I can certainly see the use case, but I would suggest not making it the default behavior.

**Comment by lexicalunit** [comment]
_From @mloskot on September 21, 2017 10:29_

@jon-v You've given a valid point and one of reasons such member has not been added to `statement` , I guess. Pity, ODBC does not provide an API for it.

The options are:

1. Do not cache at all, leave `statement` class as is.

2. Control caching at compile-time
  * `cmake -DNANODBC_ENABLE_STATEMENT_SQL_CACHE=ON` (`OFF` by default)
  * `#ifdef NANODBC_ENABLE_STATEMENT_SQL_CACHE`

3. Control at run-time
  * `statement::query_` member is always there, but empty, unless caching is enabled
  * `statement::cache_query_text(bool)` to enable/disable caching

**Comment by mloskot** [comment]
Thanks for the feedback.

I think the option 2. to enable SQL text member of `statement` at compile-time is the way to go.

/cc @jon-v, @bangusi

**Comment by mloskot** [comment]
I'm going to get this implemented for next release as the compile-time option.

**Comment by mloskot** [comment]
Due to time constraints, I'm moving this to future

**Comment by mloskot** [comment]
> I think it would be useful to cache the SQL text (eg. for logging, re-creating statements etc.)

On reflection, I yet have to see a real use case that would justify adding the member, even at compile-time - I believe we should keep things simple. The more optional features we have the more difficult it is to test the whole set.

I'm closing this for now. Feel free to re-open if there is any new data to crunch.
