### ISSUE TITLE
Call SQLFreeStmt(SQL_CLOSE) inside nanodbc::result destructor

### ISSUE THREAD

**Issue by gogis** [nanodbc/nanodbc#333]
Sometimes when result of an sql statement is being processed and an exception happens without finishing processing all of it, the statement and the connection will be in unusable state and cannot be reused because of '[Microsoft][ODBC SQL Server Driver]Connection is busy with results for another hstmt'. And I don't really see the way to reset that statmenet to be used again.

Wouldn't it be a good idea to call SQLFreeStmt(SQL_CLOSE) when nanodbc::result is being destroyed before processing all the data, so that the same statement could be used in the future?

**Comment by mloskot** [comment]
I suspect this happens when you open another result set against the same connection.

You will need to enable MARS (Multiple Active ResultSet), see
- https://www.easysoft.com/developer/languages/perl/multiple-active-statements.html
- https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars

**Comment by mloskot** [comment]
> ```c++
>     //the statement and the whole connection gets unusable for subsequent calls
>     //because nanodbc::result in destructor did not reset the cursor 
> ```

I don't see the connection (e.g. SQL Server) or the statement becoming unusable.
I can re-use the statement by re-executing it without problems, so the connection remains usable too.
Here is complete test case that shows it:

```c++

TEST_CASE_METHOD(mssql_fixture, "test_statement_usable_when_result_gone", "[mssql][statement]")
{
    auto c = connect();

    create_table(
        c,
        NANODBC_TEXT("test_statement_usable_when_result_gone"),
        NANODBC_TEXT("(a int, b varchar(10))"));
    execute(
        c, NANODBC_TEXT("insert into test_statement_usable_when_result_gone values (1, 'one');"));
    execute(
        c, NANODBC_TEXT("insert into test_statement_usable_when_result_gone values (2, 'two');"));
    execute(
        c, NANODBC_TEXT("insert into test_statement_usable_when_result_gone values (3, 'tri');"));

    nanodbc::statement s;
    s.prepare(
        c, NANODBC_TEXT("select a, b from test_statement_usable_when_result_gone order by a;"));

    auto process_data_and_throw = [](int i)
    {
        if (i == 2)
            throw std::runtime_error("a==2");
    };

    try
    {
        nanodbc::result r = s.execute();
        while (r.next())
            process_data_and_throw(r.get<int>(0));
    }
    catch (std::runtime_error e)
    {
        REQUIRE(s.open());
        nanodbc::result r = s.execute(); // statement remains usable, re-execute it
        while (r.next())
            std::cout << r.get<int>(0) << std::endl;
    }
}
```

When an open statement is re-executed, nanodbc will `SQL_CLOSE` it automatically as per
https://github.com/nanodbc/nanodbc/blob/95d4daba7b1a0b4025f43160d4916653f27407b1/nanodbc/nanodbc.cpp#L1740-L1753

I still see no reason for `SQLFreeStmt(SQL_CLOSE)` in destructor of `result`.

I suspect your application is doing something else that is causing you the problem.
I'd suggest you to check it against the conditions of `Connection is busy with results for another hstmt` error.

**Comment by gogis** [comment]
You may be right. It seems that my application is doing something wrong. Sorry for bothering and thank you for your time in investigating

**Comment by mloskot** [comment]
No problem. FYI, I've added the test case to the nanodbc tests in #334
