### ISSUE TITLE
Connection busy error in test program

### ISSUE THREAD

**Issue by paul-rta** [nanodbc/nanodbc#346]
## Environment

* nanodbc version: 2.14.0
* DBMS name/version: Microsoft SQL Server 2017 Express
* ODBC connection string: Driver=ODBC Driver 17 for SQL Server;Server=WinSQL2017\SQLEXPRESS;UID=MySQLUser;MyTopSecret
* OS and Compiler: Windows 10 Professional / Visual Studio C++ 2019 
* CMake settings: N/A

## Actual behavior
Using test application from [https://nanodbc.github.io/nanodbc/use.html], when the command...

`results = execute(connection, "select * from batch_test;", 3);`

...had been run and `show(results);` had shown the result set, the subsequent call to...

`execute(connection, "drop table if exists batch_test;");`

...resulted in an exception:

> [Microsoft][ODBC Driver 17 for SQL Server]Connection is busy with results for another command

## Expected  behavior
No exception is expected.

## Minimal Working Example
See test application on [(https://nanodbc.github.io/nanodbc/use.html)]

Subsequent experiments showed that, if a local `nanodbc::result` was declared that went out of scope prior to the call to...

`execute(connection, "drop table if exists batch_test;");`

...no exception occurs.  Accordingly, the test application code should be updated.

**Comment by mloskot** [comment]
For SQL Server, you need to enable MARS (Multiple Active ResultSet):
- https://www.easysoft.com/developer/languages/perl/multiple-active-statements.html
- https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars
