### ISSUE TITLE
nanodbc exceptions not containing all function output messages

### ISSUE THREAD

**Issue by thebyohazard** [nanodbc/nanodbc#361]
* DBMS name/version: MSSQL Server 2008
* OS and Compiler: ubuntu 20.04

nanodbc is not returning all of the messages printed by a stored procedure that I am trying to call.
I am calling a stored procedure in a MSSQL Server 2008 Database from a program on an ubuntu 20.04 computer using nanodbc. 
Here is an example of my code:

```
try {
	nanodbc::connection connection(get_connection_string(),sqlTimeout);
	nanodbc::statement statement(connection);
	statement.timeout(sqlTimeout);
	prepare(statement,"{CALL [Schema].[my_stored_procedure](?,?)};");
	statement.bind(0, param1_.c_str());
	statement.bind(1, param2_.c_str());
	statement.execute();
}
catch(const std::exception& e) {
	cout << "Could not call procedure [Schema].my_stored_procedure: " << e.what();
}
```

Most of the time, the procedure runs fine, but sometimes the procedure fails to run and I am trying to figure out why. 
If I run procedures in MSSQL Server Management Studio and it fails, I can see multiple messages printed out by a SP, with the final one being the actual error. This is what I would expect to be the output.
However, when the procedure fails using nanodbc, the exception does not contain all the messages that the procedure returns, but only the first one.
For example, if the developer of the procedure has print statements in the procedure, then only the first print statement is shown.
Or if an ansi warning happens first then that is the only thing shown. Here is example output:

> Could not call procedure [Schema].my_stored_procedure: /path/to/nanodbc.cpp:1684: 0100: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Warning: Null value is eliminated by an aggregate or other SET operation. 

There are usually four such warning messages in the current procedure that is failing, but only one is shown. Is there a setting I am missing that would allow me to see the rest of the messages?

**Comment by mloskot** [comment]
Yes, we have also noticed that sometimes not all diagnostics is not collected. Your case may be related to this idea https://github.com/nanodbc/nanodbc/issues/315

**Comment by thebyohazard** [comment]
#315 definitely addresses my concerns. I'll continue conversation there.
