### ISSUE TITLE
error C2665: 'std::list<nanodbc::connection::attribute,std::allocator<nanodbc::connection::attribute>>::push_back': no overloaded function could convert all the argument types

### ISSUE THREAD

**Issue by wkriener** [nanodbc/nanodbc#363]
## Environment

* nanodbc version: 2.15.0
* OS and Compiler: Windows 11, Visual Studio Community 2022 v17.4.1

## Actual behavior

line 1117 : attributes.push_back({SQL_ATTR_ASYNC_DBC_FUNCTIONS_ENABLE, SQL_IS_UINTEGER, SQL_ASYNC_DBC_ENABLE_ON});
won't compile
...nanodbc.cpp(1117): error C2665: "std::list<nanodbc::connection::attribute,std::allocator<nanodbc::connection::attribute>>::push_back": Keine überladene Funktion konnte alle Argumenttypen konvertieren...

## Expected  behavior

nanodbc version 2.14. compiles an works as expected

**Comment by wkriener** [comment]
sorry, I missed to add:
with "set(CMAKE_CXX_STANDARD 14)" it compiles. with 17 or higher it does not compile.

**Comment by mloskot** [comment]
This is related to recent changes in https://github.com/nanodbc/nanodbc/pull/353 
/cc @detule

**Comment by wkriener** [comment]
Thank You for advice.

**Comment by detule** [comment]
Hi - thanks:

I *think* [this](https://github.com/detule/nanodbc/commit/caa541da199b02b316e7ff0adc08e5d15fe5829a) may address the issue; @wkriener if you are up for it, do you mind giving it a try? FWICT it passes the Windows CI builds, but those are older toolchains than what you are using.

Sorry about that @mloskot ; don't have a Windows box at home.  I'll clean this up, and submit it as a PR this weekend / early next week.

**Comment by mloskot** [comment]
@detule It is our fault that we have neglected the CI setup not adding builds with latest Visual Studio.
I'll try fix it soon https://github.com/nanodbc/nanodbc/issues/364

**Comment by wkriener** [comment]
Hi,
@detule with described changes in source files I can compile (and run) project under windows 11 (as described above) and Mac OS X Monterey using cxx standard 17 and even higher. Thank You!

**Comment by mloskot** [comment]
@detule Thank you. Please, could you submit PR with the fix?
