### ISSUE TITLE
Invalid descriptor index

### ISSUE THREAD

**Issue by sasichkamega** [nanodbc/nanodbc#397]
## Environment

* nanodbc version: da555252edd66888d063c2616bbd38f2b9f0d79a
* DBMS name/version: `16.00.4085`
* ODBC connection string: `DRIVER={SQL Server};SERVER=SQLTEST;Trusted_Connection=yes;AutoTranslate=Yes;`
* OS and Compiler: win10, msvc
* CMake settings: 
![img](https://github.com/nanodbc/nanodbc/assets/15817985/155f2f2d-5b2d-4f15-b264-649acd868e13)

## Actual behavior

When retrieving `test` field data from a query:

```sql
SELECT CAST('test' as NVARCHAR(MAX)), CAST('statusAudif' as NVARCHAR(100))
```
An exception with error `07009: [Microsoft][ODBC SQL Server Driver] Invalid descriptor index` is thrown.

But if change the query making `NVARCHAR(MAX)` and the field too, everything works as expected.

```sql
SELECT CAST('test' as NVARCHAR(MAX)), CAST('statusAudif' as NVARCHAR(MAX))
```
## Expected  behavior

The same behavior of the two queries above is expected

## Minimal Working Example

```c++
int main() {
  nanodbc::connection connection = nanodbc::connection(
    "DRIVER={SQL Server};SERVER=SQLTEST;Trusted_Connection=yes;AutoTranslate=Yes;"
  );

  nanodbc::result result = nanodbc::execute(
    connection,
    //"SELECT CAST('test' as NVARCHAR(MAX)), CAST('statusAudif' as NVARCHAR(MAX))" //ALL OK
    "SELECT CAST('test' as NVARCHAR(MAX)), CAST('statusAudif' as NVARCHAR(100))" //fails
  );
  for (auto row : result) {
    row.get<std::string>(0); //throws here
  }
}
```

**Comment by mloskot** [comment]
This is a known issue and it is not a bug in nanodbc.
If you searched our archives here on GitHub, you'd have found number of references with details:

- https://github.com/nanodbc/nanodbc/issues/228 - a must read
- https://github.com/nanodbc/nanodbc/pull/227
- https://github.com/nanodbc/nanodbc/discussions/309

We even have a test case for that:
https://github.com/nanodbc/nanodbc/blob/71b7f0b9db847b798ae0b2c48f3d1f3ab68c1f4d/test/mssql_test.cpp#L564-L571

**Comment by sasichkamega** [comment]
Ow! Thanks for the information!
