### ISSUE TITLE
Requesting float type data after text in SELECT query cause problem

### ISSUE THREAD

**Issue by ffreality** [nanodbc/nanodbc#408]
I have an MSSQL Express 2022 test server and my table structure is like this
`id (int) | name (text) | address (text) | phone (text) | notes (text) | exprience (float)|`

I store the result like this to access data multiple times without executing query again.

```
int32 Index_Row = 0;
TMap<FVector2D, FNANODBC_DataValue> Temp_Data;

try
{
	const int32 ColumnCount = In_Result.columns();

	while (In_Result.next())
	{
		for (int32 Index_Column = 0; Index_Column < ColumnCount; Index_Column++)
		{
			const int32 DataType = In_Result.column_datatype(Index_Column);
			const FString DataTypeName = UTF8_TO_TCHAR(In_Result.column_datatype_name(Index_Column).c_str());

			FNANODBC_DataValue EachData;
			EachData.DataType = DataType;
			EachData.DataTypeName = DataTypeName;

			if (DataType == -1 || DataType == -9)
			{
				EachData.ValString = UTF8_TO_TCHAR(In_Result.get<nanodbc::string>(Index_Column).c_str());
				EachData.ValueRepresentation = EachData.ValString;
			}

			if (DataType == 4)
			{
				EachData.ValInt32 = In_Result.get<int>(Index_Column);
				EachData.ValueRepresentation = FString::FromInt(EachData.ValInt32);
			}

			if (DataType == 6)
			{
				EachData.ValFloat = In_Result.get<float>(Index_Column);
				EachData.ValueRepresentation = FString::SanitizeFloat(EachData.ValFloat);
			}

			Temp_Data.Add(FVector2D(Index_Row, Index_Column), EachData);
		}

		Index_Row += 1;
	}
}

catch (const std::exception& Exception)
{
	FString Out_Code = Exception.what();
}

```

Problem is
`SELECT id, exprience, notes, address, name, phone FROM ue5_test.dbo.Table_1 WHERE id>=1`
this query works as intended but the one at the below doesn't.
`SELECT id, notes, address, name, phone, exprience FROM ue5_test.dbo.Table_1 WHERE id>=1`

As it like same data types should be side by side.
I am a graphics programmer but not database or ODBC expert.
So, sorry if this is an amateur question.

But is there any rule about data types for ODBC ?

**Comment by detule** [comment]
Hi @ffreality :

I think you are coming up against a limitation of some drivers that require "long/unbound" data fields to enter the query *after* the fixed-width fields.

You can:
* Reorganize your query so that long fields come at the end ( probably easiest ); or
* If you have limited control in how the query is submitted, you could unbind buffers for any fixed-width fields past the first long field ( consider for example [this excellent investigation](https://github.com/nanodbc/nanodbc/commit/f75bc90f19e18d7edf7a073dbc3b0c19ca029bcd) ), or
* Try and experiment with different drivers.  For example, `FreeTDS` does not have this limitation.  Then again no driver is perfect, in particular **writing** with `FreeTDS` can be more challenging ( compared to the OEM SQL Server driver ).

**Comment by ffreality** [comment]
> Hi @ffreality :
> 
> I think you are coming up against a limitation of some drivers that require "long/unbound" data fields to enter the query _after_ the fixed-width fields.
> 
> You can:
> 
> * Reorganize your query so that long fields come at the end ( probably easiest ); or
> * If you have limited control in how the query is submitted, you could unbind buffers for any fixed-width fields past the first long field ( consider for example [this excellent investigation](https://github.com/nanodbc/nanodbc/commit/f75bc90f19e18d7edf7a073dbc3b0c19ca029bcd) ), or
> * Try and experiment with different drivers.  For example, `FreeTDS` does not have this limitation.  Then again no driver is perfect, in particular **writing** with `FreeTDS` can be more challenging ( compared to the OEM SQL Server driver ).

Hi @detule and thank you very much for your answer.

- Using `FreeTDS` is not an option because its GPL license. Unreal Engine forbids it. Maybe I can use [tdscpp](https://github.com/maharmstone/tdscpp) but it has very few users and it will work only with MSSQL. So, it is not feasable for me.
- Organizing query solves problem. If I put float, datetime and time to start, this will be open source plugin. So, I don't want to change users query.
- `unbind` buffer partially solves problem. For example, if I put `In_Result.unbind();` to start, this query works
`SELECT id, notes, address, name, phone, exprience FROM ue5_test.dbo.Table_1 WHERE id>=1`

but if I added columns with time and datetime type, it stops working again.
So, where should I put `In_Result.unbind(); or In_Result.unbind(Index_Column); `?

```
		In_Result.unbind();
		const int32 ColumnCount = In_Result.columns();

		while (In_Result.next())
		{
			for (int32 Index_Column = 0; Index_Column < ColumnCount; Index_Column++)
			{
				const int32 DataType = In_Result.column_datatype(Index_Column);
				const FString DataTypeName = UTF8_TO_TCHAR(In_Result.column_datatype_name(Index_Column).c_str());
				const FString ColumnName = UTF8_TO_TCHAR(In_Result.column_name(Index_Column).c_str());

				FNANODBC_DataValue EachData;
				EachData.DataType = DataType;
				EachData.DataTypeName = DataTypeName;
				EachData.ColumnName = ColumnName;

				switch (DataType)
				{
					case -9:
					{
						// MSSQL's "time" dateType is an nvarchar, too.

						EachData.ValString = UTF8_TO_TCHAR(In_Result.get<nanodbc::string>(Index_Column).c_str());
						EachData.ValueRepresentation = EachData.ValString;
						break;
					}

					case -2:
					{
						nanodbc::timestamp TimeStamp = In_Result.get<nanodbc::timestamp>(Index_Column);

						FDateTime DateTime = UKismetMathLibrary::MakeDateTime(TimeStamp.year, TimeStamp.month, TimeStamp.day, TimeStamp.hour, TimeStamp.min, TimeStamp.sec, TimeStamp.fract);
						EachData.ValDateTime = DateTime;
						EachData.ValueRepresentation = DateTime.ToString();

						break;
					}

					case -1:
					{
						EachData.ValString = UTF8_TO_TCHAR(In_Result.get<nanodbc::string>(Index_Column).c_str());
						EachData.ValueRepresentation = EachData.ValString;

						break;
					}

					case 4:
					{
						EachData.ValInt32 = In_Result.get<int>(Index_Column);
						EachData.ValueRepresentation = FString::FromInt(EachData.ValInt32);

						break;
					}

					case 6:
					{
						
						EachData.ValFloat = In_Result.get<float>(Index_Column);
						EachData.ValueRepresentation = FString::SanitizeFloat(EachData.ValFloat);

						break;
					}

					case 93:
					{
						nanodbc::date Section_Date = In_Result.get<nanodbc::date>(Index_Column);
						nanodbc::time Section_Time = In_Result.get<nanodbc::time>(Index_Column);

						FDateTime DateTime = UKismetMathLibrary::MakeDateTime(Section_Date.year, Section_Date.month, Section_Date.day, Section_Time.hour, Section_Time.min, Section_Time.sec);
						EachData.ValDateTime = DateTime;
						EachData.ValueRepresentation = DateTime.ToString();

						break;
					}

					default:
					{
						break;
					}
				}
				
				Temp_Data.Add(FVector2D(Index_Row, Index_Column), EachData);
			}

			Index_Row += 1;
		}
```

**Comment by detule** [comment]
Hi there:

* Kind of confused on your approach for `93 / SQL_C_TIMESTAMP` - that seems a bit suspect.  This was said elsewhere, but you shouldn't query the same column twice.
* Actually not sure I understand your handling of -2 ( BINARY? ) either, but I didn't try really hard there.
* I would point you again to https://github.com/nanodbc/nanodbc/commit/f75bc90f19e18d7edf7a073dbc3b0c19ca029bcd as that investigation has good notes on when unbinding helps and when it doesn't.
* Having said that, I think we are squarely away from issues with `nanodbc` so we should probably close the issue here look to move this somewhere else ( sorry! ).

**Comment by ffreality** [comment]
> Hi there:
> 
> * Kind of confused on your approach for `93 / SQL_C_TIMESTAMP` - that seems a bit suspect.  This was said elsewhere, but you shouldn't query the same column twice.
> * Actually not sure I understand your handling of -2 ( BINARY? ) either, but I didn't try really hard there.
> * I would point you again to [f75bc90](https://github.com/nanodbc/nanodbc/commit/f75bc90f19e18d7edf7a073dbc3b0c19ca029bcd) as that investigation has good notes on when unbinding helps and when it doesn't.
> * Having said that, I think we are squarely away from issues with `nanodbc` so we should probably close the issue here look to move this somewhere else ( sorry! ).

- Even if SQL stores `timestamp` as `binary`, I need it as Unreal Engine's FDateTime structure. I or any Unreal Engine can't do anything with just binary data for that case.
- DataType showed me that `DateTime` is 93. Not TimeStamp. and there was no predefined `DateTime`. In order to get both date and time, I needed to query same column twice.

**Comment by ffreality** [comment]
> Hi there:
> 
> * Kind of confused on your approach for `93 / SQL_C_TIMESTAMP` - that seems a bit suspect.  This was said elsewhere, but you shouldn't query the same column twice.
> * Actually not sure I understand your handling of -2 ( BINARY? ) either, but I didn't try really hard there.
> * I would point you again to [f75bc90](https://github.com/nanodbc/nanodbc/commit/f75bc90f19e18d7edf7a073dbc3b0c19ca029bcd) as that investigation has good notes on when unbinding helps and when it doesn't.
> * Having said that, I think we are squarely away from issues with `nanodbc` so we should probably close the issue here look to move this somewhere else ( sorry! ).

@detule
- Even if SQL stores `timestamp` as `binary`, I need it as Unreal Engine's `FDateTime` structure.
I or any Unreal Engine user can't do anything with just binary data for that case.
- `DataType` showed me that `DateTime` is 93. Not `TimeStamp`. and there was no predefined `DateTime`. In order to get both date and time, I needed to query same column twice.

**Comment by mloskot** [comment]
FYA, https://github.com/nanodbc/nanodbc/discussions/410#discussioncomment-9975988
