### ISSUE TITLE
error LNK2019: reference to unresolved external character __std_find_trivial_1

### ISSUE THREAD

**Issue by Kokainym** [nanodbc/nanodbc#419]
* nanodbc version: 2.14
* OS and Compiler: Windows 10, VS2022
* CMake settings: by default

I tried to embed the nanodbc library into my project. The project contains the following dependencies.
- libnodave
- imgui (glad, glfw)
- skia
- nlohmann

The following error occurs:
`1>nanodbc.lib(nanodbc.obj) : error LNK2019: reference to unresolved external character __std_find_trivial_1 в функции "unsigned char * __cdecl __std_find_trivial<unsigned char,char>(unsigned char *,unsigned char *,char)" (??$__std_find_trivial@ED@@YAPEAEPEAE0D@Z).  
1>..\bin\sawline\Debug-windows-x86_64\sawline.exe : fatal error LNK1120: unauthorized external elements: 1`  

By brute force I found out that the error occurs when adding a string with the connection construct. Without it, the error does not occur, but using the library without connection is absurd).

**Comment by mloskot** [comment]
I have very little idea what could be causing the issue and I doubt this issue has anything to do with the nanodbc.
For example, another mysterious story about `unresolved __std__find_trivial...` is here, https://github.com/firebase/flutterfire/issues/10992#issuecomment-1676426426, magically solved by upgrade of VS 2022.

Perhaps don't hard code any non-ASCII characters in your C++ source files, unless you save them with correct Unicode-based encoding.
