### ISSUE TITLE
recent_error truncate gbk strings

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#6]
_From @ddmly on September 13, 2017 14:0_

## Environment

* nanodbc version: master/20170912
* DBMS name/version: sql server 2008
* ODBC connection string: Driver=ODBC Driver 13 for SQL Server;Server=x;Uid=sa;Pwd=x;database=test
* OS and Compiler: windows, vs2013, gbk
* CMake settings: None, compile nanodbc together with test.cpp

## Actual behavior
truncate gbk string shows [....?]
## Expected  behavior
show all error message [...........]
## Minimal Working Example
sql = "drop table if exists test.simple_test"; // sql server not support, will throw error

## Temporary fixed
```
- if (success(rc) && total_bytes > 0)
+ if (success(rc) && total_bytes > SQL_MAX_MESSAGE_LENGTH)
            sql_message.resize(static_cast<std::size_t>(total_bytes) + 1);
- result += nanodbc::string(sql_message.begin(), sql_message.end());
+ result += nanodbc::string(sql_message.begin(), sql_message.begin()+ total_bytes);
```

_Copied from original issue: lexicalunit/nanodbc#284_

**Comment by lexicalunit** [comment]
_From @mloskot on September 15, 2017 23:58_

Thanks for the report.
I'll try to get the patch in, and add test for error messages too. (would be easier with pull request though)

**Comment by mloskot** [comment]
Should be fixed by https://github.com/nanodbc/nanodbc/pull/298
