### ISSUE TITLE
[MySQL] Is find_tables not supported?

### ISSUE THREAD

**Issue by changtj** [nanodbc/nanodbc#65]
## Environment

* nanodbc version:
2.12
* DBMS name/version:
mysql
* ODBC connection string:
* OS and Compiler:
windows, vs2017
* CMake settings:

## Minimal Working Example

```
nanodbc::catalog cat(m_conn);
td::list <std::string> list_cat = cat.list_catalogs();
//is catalog   databased?
std::list <std::string> list_database = cat.list_schemas();
// list_database is empty...
std::string str_dbms_name = m_conn.dbms_name();
std::string str_empty = "%";
//nanodbc::catalog::tables tables = cat.find_tables( table, NANODBC_TEXT("TABLE"), get_database(), "");
nanodbc::catalog::tables tables = cat.find_tables(str_empty, str_empty, str_empty);

while (tables.next())
{
...
//can't reach here.
}
```

**Comment by mloskot** [comment]
Relevant test is included in tests suite, see how it is used in https://github.com/nanodbc/nanodbc/blob/master/test/test_case_fixture.h#L566-L599
And, MySQL is exercised with the test, see https://github.com/nanodbc/nanodbc/blob/master/test/mysql_test.cpp#L137-L140
Finally, all MySQL tests succeed on Windows
https://ci.appveyor.com/project/lexicalunit/nanodbc/branch/master/job/qotv0tsrcopp7jay
and Linux
https://travis-ci.org/lexicalunit/nanodbc/builds/276752688

I suggest you review your usage of [SQLTables](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function) (`find_tables` is a very thin wrapper on top of `SQLTables`)
---

The project is being migrated to different repository, migration has not completed yet, so CI links in README may be temporarily broken.
