### ISSUE TITLE
Migrate to github.com/nanodbc/nanodbc

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#66]
_From @lexicalunit on October 13, 2017 23:20_

TODO:

- [x] Create http://github.com/nanodbc/nanodbc
- [x] Create nanodbc.io
- [x] Migrate `master` and `gh-pages`
- [x] Migrate open issues to http://github.com/nanodbc/nanodbc
- [x] Migrate closed issues to http://github.com/nanodbc/nanodbc  (not as crucial as open issues)
- [x] Merge or close outstanding PRs: https://github.com/lexicalunit/nanodbc/pulls
- [x] Update https://github.com/lexicalunit/nanodbc/blob/master/README.md to point at new repository
- [x] Migrate coverity
- [x] Migrate Travis CI
- [x] Migrate Appveyor
- [x] Migrate old releases?
- [x] Make new `release`, `latest`, and `stable` branches/tags.
- [x] Migrate source level Doxygen documentation
- [x] Migrate general github.com/lexicalunit/nanodbc links
- [x] Migrate Issues and PRs links found in the source code itself:
  ```
  test/test_case_fixture.h
  464:            // See https://github.com/lexicalunit/nanodbc/issues/249
  
  test/sqlite_test.cpp
  53:// https://github.com/lexicalunit/nanodbc/pull/154
  107:// See https://github.com/lexicalunit/nanodbc/pull/220#issuecomment-257029475
  
  test/postgresql_test.cpp
  205:        // See https://github.com/lexicalunit/nanodbc/pull/229
  
  nanodbc/nanodbc.cpp
  66:// See https://github.com/lexicalunit/nanodbc/issues/226
  ```
- [x] Enable protected branches

_Copied from original issue: lexicalunit/nanodbc#299_

**Comment by lexicalunit** [comment]
Open issues have been moved with the help of https://github-issue-mover.appspot.com/

Note that moving closed issues is possible but the tool will create the new issues as open and you have to manually close them after moving them.

**Comment by lexicalunit** [comment]
It seems like the best way to move PRs from one repo to another is to check them out locally, then push them up as branches to the new repo, then open PRs for them there. It may be best to just merge/close all outstanding PRs as soon as possible.

**Comment by lexicalunit** [comment]
http://nanodbc.io is live!

**Comment by lexicalunit** [comment]
@mloskot I think we should aim to merge all the open PRs we have here, then push those changes up to http://github.com/nanodbc/nanodbc

New PRs and issues should be opened against http://github.com/nanodbc/nanodbc

I'll update the README for http://github.com/lexicalunit/nanodbc to point at http://github.com/nanodbc/nanodbc

**Comment by lexicalunit** [comment]
_From @mloskot on October 14, 2017 21:9_

@lexicalunit 
> I think we should aim to merge all the open PRs we have here

Does it mean you agree with the changes/enhancements in the proposed PRs?

Or we take the strategy to merge and then we figure out if we like things, get rid of broken behaviours, ect. after the fact?

**Comment by lexicalunit** [comment]
_From @mloskot on October 14, 2017 21:53_

> Note that moving closed issues is possible but the tool will create the new issues as open and you have to manually close them after moving them.

A bit pity.

I wonder, simple redirction from lexicalunit/nanodbc to nanodbc/nanodbc would not work?
https://github.com/blog/1508-repository-redirects-are-here

**Comment by lexicalunit** [comment]
Interesting! That might be what we want.

**Comment by lexicalunit** [comment]
_From @mloskot on October 15, 2017 10:33_

Let me know or assign to, if you need my help

@lexicalunit Knock knock, sorry for nudging, but apparently users started submitting issues to nanodbc/nanodbc and, in case that is going to be re-imported, we may need to take some action. Do you need help, let me know.

On 15 Oct 2017 01:39, "Amy Troschinetz" <notifications@github.com> wrote:

Interesting! That might be what we want.

**Comment by lexicalunit** [comment]
_From @mloskot on October 23, 2017 8:11_

PR #296 merged into new repo

**Comment by lexicalunit** [comment]
@mloskot moved this issue from the old repo to here :)

**Comment by mloskot** [comment]
Old releases migrated

**Comment by lexicalunit** [comment]
🎉

**Comment by mloskot** [comment]
I have taken the liberty to structured a bit labels for the issues

**Comment by mloskot** [comment]
@lexicalunit How do we go about this?

- [ ] Migrate closed issues to new repository (not as crucial as open issues)

**Comment by lexicalunit** [comment]
It maybe isn't as important as long as we keep the old repository around we can always go look at those issues. There might be some tools out there for doing it though if we really want to.

**Comment by mloskot** [comment]
@lexicalunit 
> It maybe isn't as important as long as we keep the old repository around we can always go look at those issues. 

The thing is, we have number of references in code and docs like this

```
// See https://github.com/lexicalunit/nanodbc/issues/226
```

but, the `https://github.com/lexicalunit/nanodbc/issues/XXX` currently give HTTP 404 due to the Issues being disabled in the old repo.

So, I was thinking about migrating them to the new repo.
Or, we could just re-enabling the Issues in the archived repo (manually monitor them for any new additions, directing submitters to the new repo).

**Comment by mloskot** [comment]
> [x] Make new release, latest, and stable branches/tags. 

Done: release, latest and tags.

I have no idea what is the stable branch/tag supposed to be, skipped.

**Comment by mloskot** [comment]
> - [x] Migrate closed issues to http://github.com/nanodbc/nanodbc

Done, using the https://github-issue-mover.appspot.com

**Comment by mloskot** [comment]
Scan Coverity:

There is an issue with renaming lexicalunit/nanodbc to nanodbc/nanodbc or nanodbc.
Apparently, I screwed up by creating the latter two manually while I could rename the former.
Now, the names are no longer available. See details at https://stackoverflow.com/q/48175947/151641

I'm in touch with Coverity support, waiting for feedback.

**Comment by mloskot** [comment]
Coverity Scan project renamed/moved to point to nanodbc/nanodbc

https://github.com/nanodbc/nanodbc/commit/f4668ba94524f618e147196266b8361f191c8a47

BTW, regarding Coverity project renaming, be careful in future, see details at https://stackoverflow.com/a/48491718/151641

**Comment by mloskot** [comment]
> Merge or close outstanding PRs

There was only one PR dangling in the old repository.
It has been rebased and migrated to the new repo in https://github.com/nanodbc/nanodbc/pull/151

**Comment by mloskot** [comment]
> Enable protected branches

Done, for master only.

**Comment by mloskot** [comment]
I'm happy to report the migration has been completed :)
