### ISSUE TITLE
How can i get "index" in databases ?

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#67]
_From @changtj on October 23, 2017 13:0_

The question is same to the title.

_Copied from original issue: lexicalunit/nanodbc#300_

**Comment by lexicalunit** [comment]
_From @mloskot on October 23, 2017 13:49_

What do you mean exactly?
What ODBC API call you wish to use, have you grepped if it is covered by
nanodbc?

**Comment by lexicalunit** [comment]
_From @changtj on October 24, 2017 1:37_

For example, in dbms ,  object exists such as table, view, index,function.  catalog class in nanodbc has no functions that fetch "index" .

**Comment by lexicalunit** [comment]
_From @mloskot on October 24, 2017 7:0_

https://www.google.pl/search?q=odbc+list+indexes

In first five results, you get hints about possible solution, namely, `SQLStatistics`.

If that is not suitable to your needs, then you have to search catalog with regular SQL queries, that will be DBMS-specific, obviously.

**Comment by lexicalunit** [comment]
_From @mloskot on October 24, 2017 13:14_

BTW, it would be possible to add thin wrapper for `SQLStatistics` to nanodbc, why not.

**Comment by mloskot** [comment]
Closed due to no feedback
