### ISSUE TITLE
Build fails due to c++14 features but CMakeLists set to c++11

### ISSUE THREAD

**Issue by Shelnutt2** [nanodbc/nanodbc#68]
## Environment

* nanodbc version: master
* DBMS name/version: N/A
* ODBC connection string: N/A
* OS and Compiler: linux gcc-6.3
* CMake settings: N/A

## Actual behavior
Build fails due to c++14 feature (auto return) but CMakeLists.txt sets c++11

## Expected  behavior
Build succeeds

**Comment by mloskot** [comment]
Fixed in 5ea7efeaabe8a0db771680d891e02300ecdba452
