### ISSUE TITLE
Unit test broken due to Catch Version Change

### ISSUE THREAD

**Issue by Shelnutt2** [nanodbc/nanodbc#70]
## Environment

* nanodbc version: master
* DBMS name/version: N/A
* ODBC connection string: N/A
* OS and Compiler: linux gcc-6
* CMake settings: N/A

## Actual behavior
Unit test fail to build due to header missing, due to catch 2.x vs 1.x. Catch recently upgraded to Catch2 and is not backwards compatible with Catch 1.x. Since catch is currently checked out via master branch, Catch2 is being pulled in.

## Expected  behavior
Unit test build and pass

## Minimal Working Example
cmake .. && make

**Comment by mloskot** [comment]
I have just switched to Catch v2 in https://github.com/nanodbc/nanodbc/commit/7ec8ef2e73d720ef9aa8f99fca48fa8b0dc6a6fc
