### ISSUE TITLE
I can't make successfully on the latest master branch

### ISSUE THREAD

**Issue by tomthink** [nanodbc/nanodbc#75]
* nanodbc version: the latest master branch
* DBMS name/version:
* ODBC connection string:
* OS and Compiler:CentOS Linux release 7.2.1511 (Core)
* CMake settings: cmake ..

```
cd path/to/nanodbc/repository
mkdir build
cd build
cmake [Build Options] ..
make # creates shared library         ***ERROR!!!

nanodbc.cpp:1794:24: ERROR: no match for ‘operator=’ (operand types are ‘std::initializer_list<long unsigned int>’ and ‘const SQLULEN {aka const long unsigned int}’)
             value_size = param.size_;
                        ^
nanodbc.cpp:197:61: ERROR: cannot ‘SQLRETURN SQLBindParameter(SQLHSTMT, SQLUSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLSMALLINT, SQLULEN, SQLSMALLINT, SQLPOINTER, SQLLEN, SQLLEN*)’ param 6 convert ‘std::initializer_list<long unsigned int>’ to ‘SQLULEN {aka long unsigned int}’
 #define NANODBC_CALL_RC(FUNC, RC, ...) RC = FUNC(__VA_ARGS__)
                                                             ^
nanodbc.cpp:1793:24: ERROR: no match for ‘operator==’ (operand types are ‘std::initializer_list<long unsigned int>’ and ‘int’)
         if (value_size == 0)
                         ^
nanodbc.cpp:1794:24: ERROR: no match for ‘operator=’ (operand types are ‘std::initializer_list<long unsigned int>’ and ‘const SQLULEN {aka const long unsigned int}’)
             value_size = param.size_;
                             ^

nanodbc.cpp:1807:24: ERROR: no match for ‘operator=’ (operand types are ‘std::initializer_list<long unsigned int>’ and ‘int’)
             param_size = SQL_SS_LENGTH_UNLIMITED;
                               ^
```

some one can fix it?

**Comment by mloskot** [comment]
What is the compiler and what version of the compiler?

**Comment by tomthink** [comment]
It seems like there are some syntactic error ...
the version of make is : 
# make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by lexicalunit** [comment]
During the make process a C++ compiler on your system will be selected to build the library. Not all C++ compilers are supported, for example you need one that supports C++11 features to compile nanodbc. Do you know what C++ compiler you're using?

**Comment by tomthink** [comment]
What I need add to cmake Options?
the c++ compiler version is: 
g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright © 2015 Free Software Foundation, Inc.

**Comment by mloskot** [comment]
@tomthink 
>It seems like there are some syntactic error

There are no such errors in the master according to the CI builds status, see https://github.com/nanodbc/nanodbc#build-status

> g++ --version
> g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

nanodbc requires compiler with C++14 support, see explanation of nanodbc branches here https://github.com/nanodbc/nanodbc#branches

You will need to use more modern compiler, presumably GCC 5.0 (it might work with 4.9 though), see http://en.cppreference.com/w/cpp/compiler_support
