### ISSUE TITLE
SQLGetData error then Read ValueLenOrInd directly

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#8]
_From @superzmy on September 8, 2017 14:42_

## Environment

* nanodbc version: trunk
* DBMS name/version:
* ODBC connection string: ODBC 13 for SQL SERVER
* OS and Compiler: WIN7 64 VS2017
* CMake settings:

## Actual behavior
get_ref_impl<string> : SQLGetData(...) error on a varbinary field(and it's value is NULL). code didn't test success before use ValueLenOrInd and ValueLenOrInd is uninit.
## Expected  behavior
don't throw error  ? why SQLGetData error by using show() of usage.cpp
## Minimal Working Example
results.get<nanodbc::string>(col, null_value);

_Copied from original issue: lexicalunit/nanodbc#281_

**Comment by lexicalunit** [comment]
_From @mloskot on September 8, 2017 15:6_

Could you try the current master branch?

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 16:8_

I have retry by using the version of latest (u16string). By the way VS2017 has vs-2015-rc-linker-stdcodecvt-error too? I made some fix and build.
The error that can't read varbinary is still exists. This time I make somedata in the varbinary field then "show()" the result. In the function get_ref_impl(), it didn't success read the sizeof varbinary but the code of this version even don't throw error. ValueLenOrInd was used when it havn't been inited.
sql error code should be "07009 Invalid descriptor index"

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 16:10_

the latest version code about SQLGetData is weak then the master version

**Comment by lexicalunit** [comment]
_From @mloskot on September 8, 2017 16:17_

There is no trunk branch or version in nanodbc.

Your options are:
1. Use latest release
2. Use current master branch

You really need to be more specific on which version you tested.
Saying "latest version code" does not help as it is unclear if you mean latest release or latest master branch.


Finally, if you know what is the error and what is missing from nanodbc, then you are welcome to submit pull request (including test for your use case if it is missing from [test/mssql_test.cpp](https://github.com/lexicalunit/nanodbc/blob/master/test/mssql_test.cpp)

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 16:55_

I use svn so I get an trunk, I think it's master in git. My "latest" means 2.12.4.
Both of them failed. None of them has test the result of SQLGetData.
I'm trying to know why SQLGetData cause an error on varbinary field, but I'm new to ODBC.

Make table has a varbinary(50)
```
nanodbc::statement s{ connect, u"select * from [user]" };
nanodbc::result result = s.execute();
show(result);   //<- 07009 Invalid descriptor index
```

**Comment by lexicalunit** [comment]
_From @mloskot on September 8, 2017 17:4_

> I use svn so I get an trunk

Official nanodbc repository is git on GitHub. There is no (official) SVN repository for nanodbc. 

I have no way to say what kind of nanodbc source code you are pulling for that mysterious SVN repository. 

Please, forget any SVN and try code from this master branch, https://github.com/lexicalunit/nanodbc/tree/master, and nowhere else.

> `select * from [user]`

If `user` table contains long data/variable-length columns (eg. `VARBINARY`) and columns of simple types (eg. `INT`), you can not query them in arbitrary order.  Applications should make sure to place long data columns at the end of the select list. 

You can learn about the whole set of ODBC restrictions here: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 17:13_

First of all thank you very much to tell me the limit..
2 Github give us the ability to use SVN like Github for easy.

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 17:19_

3. No matter what, "To use ValueLenOrInd before it's inited“ is an undefined action.
Count you replace them by "SQLLEN ValueLenOrInd = -1;" or something else

**Comment by lexicalunit** [comment]
_From @mloskot on September 8, 2017 17:38_

> 2 Github give us the ability to use SVN like Github for easy.

Default on GitHub is git mode. If you use something else, you should make it clear, otherwise confusion leads to unnecessary questions.

> No matter what, "To use ValueLenOrInd before it's inited“ is an undefined action.

The pattern used in nanodbc is like this:

```
SQLLEN ValueLenOrInd;
...
NANODBC_CALL_RC(
    SQLGetData,
    rc,
    handle,          // StatementHandle
    column + 1,      // Col_or_Param_Num
    SQL_C_BINARY,    // TargetType
    buffer,          // TargetValuePtr
    buffer_size,     // BufferLength
    &ValueLenOrInd); // StrLen_or_IndPtr
if (ValueLenOrInd > 0)   // <----------------- ValueLenOrInd  always set with a value by SQLGetData
{
...
}
```

* `ValueLenOrInd` is [output](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function) argument, so `SQLGetData` sets it with a value.

* `ValueLenOrInd` is never null pointer and `SQLGetData`  always sets it with a value. So, this [documented restriction](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function) does not happen: "*If the data is NULL and StrLen_or_IndPtr was a null pointer, SQLGetData returns SQLSTATE 22002 (Indicator variable required but not supplied).*"

I might be missing something, but as far I do not see any place where `ValueLenOrInd` is **used** before it is initialised.

If I'm missing something and there indeed is a place where `ValueLenOrInd` is used before initialised, please open the issue, point out line numbers or, ideally, submit pull request with a fix. Thanks.

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 19:32_

SQLGetData is failed when varbinary column is before other. 
And it will not set ValueLenOrInd (I has debuged in VS2017).
For test, I init ValueLenOrInd  = 5, and stepover SQLGetData and it's 5. Then nanodbc append something.

**Comment by lexicalunit** [comment]
_From @superzmy on September 8, 2017 19:36_

Maybe I don't have the privilege to open issue. And that pull request is hard for me because I just use svn

**Comment by lexicalunit** [comment]
_From @mloskot on September 8, 2017 20:37_

> SQLGetData is failed when varbinary column is before other.
> And it will not set ValueLenOrInd (I has debuged in VS2017).
> For test, I init ValueLenOrInd = 5, and stepover SQLGetData and it's 5. Then nanodbc append something.

OK, now that makes sense.
It might be ODBC API generic or ODBC driver specific behaviour.
Anyhow, that is something too look into. Thanks!

**Comment by mloskot** [comment]
This issue is somewhat related to #17, see https://github.com/nanodbc/nanodbc/issues/17#issuecomment-336588884

**Comment by mloskot** [comment]
> ```
> show(result);   //<- 07009 Invalid descriptor index
> ```

This is related to bound/unbound and out-of-order retrieval as discussed in https://github.com/nanodbc/nanodbc/issues/228 and improved in https://github.com/nanodbc/nanodbc/pull/236
