### ISSUE TITLE
cannot use in visual studio community 2015

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#88]
_From @tjnapster555 on October 31, 2015 17:35_

i am getting so many errors when i use it in visual studio 2015 . VIsual studio give error that i didn't include this #include "stdafx.h"' header in nanodbc.cpp file but when i include i get more errors

argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   742
Warning C4627   '#include "nanodbc.h"': skipped when looking for precompiled header use ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   7
Warning C4627   '#include <algorithm>': skipped when looking for precompiled header use ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   9
Warning C4627   '#include <cassert>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   10
Warning C4627   '#include <clocale>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   11
Warning C4627   '#include <cstdint>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   12
Warning C4627   '#include <cstdio>': skipped when looking for precompiled header use    ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   13
Warning C4627   '#include <cstring>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   14
Warning C4627   '#include <ctime>': skipped when looking for precompiled header use ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   15
Warning C4627   '#include <iomanip>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   16
Warning C4627   '#include <map>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   17
Warning C4627   '#include <sstream>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   18
Warning C4627   '#include <boost/locale/encoding_utf.hpp>': skipped when looking for precompiled header use ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   21
Warning C4627   '#include <codecvt>': skipped when looking for precompiled header use   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   23
Warning C4005   'NANODBC_ODBC_VERSION': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   33
Warning C4627   '#include <windows.h>': skipped when looking for precompiled header use ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   52
Warning C4627   '#include <sql.h>': skipped when looking for precompiled header use ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   55
Warning C4627   '#include <sqlext.h>': skipped when looking for precompiled header use  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   56
Warning C4005   'NANODBC_TEXT': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   78
Warning C4005   'NANODBC_SNPRINTF': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   79
Warning C4005   'NANODBC_STRFTIME': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   80
Warning C4005   'NANODBC_STRLEN': macro redefinition    ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   81
Warning C4005   'NANADBC_STRNCMP': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   82
Warning C4005   'NANODBC_UNICODE': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   83
Warning C4005   'NANODBC_SQLCHAR': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   84
Warning C4005   'NANODBC_TEXT': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   93
Warning C4005   'NANODBC_SNPRINTF': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   94
Warning C4005   'NANODBC_STRFTIME': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   95
Warning C4005   'NANODBC_STRLEN': macro redefinition    ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   96
Warning C4005   'NANADBC_STRNCMP': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   97
Warning C4005   'NANODBC_UNICODE': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   98
Warning C4005   'NANODBC_SQLCHAR': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   99
Warning C4005   'NANODBC_TEXT': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   101
Warning C4005   'NANODBC_SNPRINTF': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   102
Warning C4005   'NANODBC_STRFTIME': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   103
Warning C4005   'NANODBC_STRLEN': macro redefinition    ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   104
Warning C4005   'NANADBC_STRNCMP': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   105
Warning C4005   'NANODBC_UNICODE': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   106
Warning C4005   'NANODBC_SQLCHAR': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   107
Warning C4627   '#include <iostream>': skipped when looking for precompiled header use  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   128
Warning C4005   'NANODBC_CALL_RC': macro redefinition   ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   146
Warning C4005   'NANODBC_CALL': macro redefinition  ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   147
Error (active)      PCH warning: header stop cannot be in a macro or #if block.  An IntelliSense PCH file was not generated.    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   163
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   258
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   273
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   695
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   1110
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   1255
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   1334
Error (active)      argument of type "SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"    ConsoleApplication7 c:\Users[username]\Documents\Visual Studio 2015\Projects\ConsoleApplication7\ConsoleApplication7\nanodbc.cpp   2097
Error   C1010   unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?    ConsoleApplication7 c:\users[username]\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp   3421

_Copied from original issue: lexicalunit/nanodbc#50_

**Comment by mloskot** [comment]
_From @lexicalunit on October 31, 2015 17:45_

Hrm. I don't have a windows machine to test on but the `"SQLCHAR *" is incompatible with parameter of type "SQLWCHAR *"` errors indicate that this is probably related to Unicode issues. Try adding `NANODBC_USE_UNICODE=1` to your compile definitions or you can simply add the following to the top of `nanodbc.cpp`

``` cpp
#define NANODBC_USE_UNICODE 1
```

The issue might also have to do with `stdafx.h`. I had to google for that and it seems like it's a VS feature having to do with precompiled headers. From [this post on stackoverflow](http://stackoverflow.com/a/4726838) it looks like if you want to use `stdafx.h`, you have to make sure to `#include` it in your `.cpp` files too. So maybe adding the following to `nanodbc.cpp` is necessary in your case.

``` cpp
#include "stdafx.h"
```

If you try each of these solutions and then both of them together in combination, please let me know if it helps you get things working.

**Comment by mloskot** [comment]
_From @tjnapster555 on October 31, 2015 17:58_

C2855   command-line option '/d1safedelete' inconsistent with precompiled header    ConsoleApplication7 c:\users\tjnapster555\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp 2
Error   C2855   command-line option '/d1autoclassinit' inconsistent with precompiled header ConsoleApplication7 c:\users\tjnapster555\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp 2
Error   C2855   command-line option '/sdl' inconsistent with precompiled header ConsoleApplication7 c:\users\tjnapster555\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp 2
Warning C4651   '/D_GUARDOVERFLOW_CRT_ALLOCATORS=1' specified for precompiled header but not for current compile    ConsoleApplication7 c:\users\tjnapster555\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp 2
Warning C4244   'argument': conversion from 'SQLINTEGER' to 'SQLSMALLINT', possible loss of data    ConsoleApplication7 c:\users\tjnapster555\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp 270
Warning C4244   'argument': conversion from 'SQLINTEGER' to 'SQLSMALLINT', possible loss of data    ConsoleApplication7 c:\users\tjnapster555\documents\visual studio 2015\projects\consoleapplication7\consoleapplication7\nanodbc.cpp 285

**Comment by mloskot** [comment]
_From @tjnapster555 on October 31, 2015 17:58_

it gets worse

**Comment by mloskot** [comment]
_From @lexicalunit on October 31, 2015 18:3_

You might also try not making `nanodbc.cpp` a precompiled header. I'm not sure exactly how to do this or if it makes sense for your use case, but my guess is removing the file from your project's `stdafx.h` file and/or changing project build settings. Sorry I can't be of more help. If I had a windows machine with VS2015 I could do a lot more I'm sure :(

**Comment by mloskot** [comment]
_From @tjnapster555 on October 31, 2015 18:3_

which compiler you use when you develop your project ?

**Comment by mloskot** [comment]
_From @tjnapster555 on October 31, 2015 18:7_

i might able to use that compiler in my windows machine

**Comment by mloskot** [comment]
_From @lexicalunit on October 31, 2015 18:8_

I test using the compilers gcc and clang on OS X, and I've tested using xcodebuild and CMake build systems. I believe gcc, clang, and CMake are all available on Windows too. I know other Windows users have had luck building nanodbc in the past, but I'm not sure if they were using the 2015 version of VS or not.

**Comment by mloskot** [comment]
_From @tjnapster555 on October 31, 2015 18:30_

can you tell me the c++ standard you use , because i am getting error related to c++ 11 in code block gcc compiler

**Comment by mloskot** [comment]
_From @tjnapster555 on October 31, 2015 18:31_

error 'wstring_convert' is not a member of 'std'

**Comment by mloskot** [comment]
_From @lexicalunit on October 31, 2015 19:10_

Nanodbc is built using the C++11 or C++14 standards. Older versions (1.x) could be built using the C++03 standard. You might read through issue #23, because it might be similar to the issue you're seeing with `wstring_convert`.

**Comment by gcallxpert** [comment]
Right click on Project > Properties >  Advanced > Character Set > Use Multi-Byte Character Set solved this issue for me
