### ISSUE TITLE
SQLCompleteAsync not found in odbc32.dll on Win 7 64 bit SP1

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#89]
_From @manwithahammer on November 10, 2015 16:33_

I am on Visual Studio 2015. When I write code that uses nanodbc on Win 7 64 bit SP1, everything compiles and builds fine. But during run time, I get an "Entry Point Not Found" error. The issue doesn't happen in Windows 8 or Windows 10. Inspecting odbc32.dll in Dependency Walker, I see that the function is exported in Win8 and Win10, but not in Win7. I am not sure what to do about it, as I haven't been able to find a way to somehow upgrade odbc32.dll itself. What is strange is that `SQL_ATTR_ASYNC_STMT_EVENT` is defined in `sqlext.h`, which in turn depends on ODBCVER which is set to be `0x0380` in `sql.h`. I can get around the problem by doing

```
#define ODBCVER 0x0351
#define SQL_OV_ODBC3_80 3UL
```

in nanodbc.cpp right before the `#include <sql.h>`, but it feels like it's a bit of a hack. Is this an acceptable solution or is there a cleaner way to solve this issue?

_Copied from original issue: lexicalunit/nanodbc#56_

**Comment by mloskot** [comment]
_From @lexicalunit on November 10, 2015 16:48_

Thank you for the detailed diagnostics here! I'm sure it will help others with similar issues in the future. Unfortunately I'm generally at a loss with regards to Windows issues. The last Windows edition I used was 95, and I haven't really touched it since then.

Are you actually wanting to use `SQLCompleteAsync()` in your application? If simply having asynchronous functionality be enabled is causing the "Entry Point Not Found" issue for you on Windows 7, and you're not even using that, then setting `ODBCVER` to something earlier than `0x0380` will effectively disable asynchronous functionality in nanodbc. But you're right it's not the cleanest solution.

Another option would be to add a compile flag to optionally disable asynchronous functionality in nanodbc. You would then enable that flag when building for Windows 7. Let me know what you think.

**Comment by mloskot** [comment]
_From @manwithahammer on November 10, 2015 17:10_

I am not using asynchronous calls at all. The is for a C++ financial pricing application which only reads from the DB, doesn't write to it, so it's all blocking calls.
I can keep the `#define`s there, it's not a huge deal. A compile flag would be nice but I don't know if it's worth your time to put in there.
Keep up the good work, thanks!

**Comment by mloskot** [comment]
_From @kentf on November 10, 2015 19:53_

Hi, as I understand it, the 3.80 version of the ODBC API introduced the asynchronous methods. The API is present in the ODBC header files in Visual Studio 2015, and possibly in Visual Studio 2013 too. That means it's perfectly fine to build applications using this API, while developing in Windows 7.

However, you won't be able to run the newer API on Windows 7, because the highest available version of the driver is 3.50.

If sorry if there are any factual mistakes here, as I had this issue a couple of months ago and I remember this from the top of my head.

**Comment by mloskot** [comment]
_From @manwithahammer on November 10, 2015 19:58_

Thanks for the input, Kent. This is exactly what I did above, set the ODBC version manually to 3.51, which prevents nanodbc from linking against the asynchronous API.
Strange though that it's impossible to update the ODBC API on Windows 7.

**Comment by mloskot** [comment]
_From @lexicalunit on November 10, 2015 20:10_

Oh right, you could also define `NANODBC_ODBC_VERSION` to be `0x0351`. Nanodbc will use that define for the ODBC version if it's defined. If that isn't defined, it defaults to `SQL_OV_ODBC3_80` or  `SQL_OV_ODBC3`, depending. That should hopefully be sufficient without having to modify the `cpp` source or manually define `SQL_OV_ODBC3_80` like you mentioned.

Here's the current logic, the comments should make it clear what the intent is here:

``` cpp
// Default to ODBC version defined by NANODBC_ODBC_VERSION if provided.
#ifndef NANODBC_ODBC_VERSION
    #ifdef SQL_OV_ODBC3_80
        // Otherwise, use ODBC v3.8 if it's available...
        #define NANODBC_ODBC_VERSION SQL_OV_ODBC3_80
    #else
        // or fallback to ODBC v3.x.
        #define NANODBC_ODBC_VERSION SQL_OV_ODBC3
    #endif
#endif
```

**Comment by mloskot** [comment]
_From @manwithahammer on November 10, 2015 20:17_

Doing this:

```
#define NANODBC_ODBC_VERSION 0x0351
#include <Engine/Tools/nanodbc.h>
```

Didn't work for me. Am I doing something wrong? I couldn't find `NANODBC_ODBC_VERSION` anywhere in the source code.

**Comment by mloskot** [comment]
_From @lexicalunit on November 10, 2015 22:17_

The code I posted above should exist in the `src/nanodbc.cpp` file in the most recent version of nanodbc. You'll have to ensure that `NANODBC_ODBC_VERSION` is defined for the `nanodbc.cpp` translation unit; defining it in the header file in one of your source files will unfortunately not work as intended. Since you're using Windows VC++ I'm not sure exactly how to do this, but it'd be in the build settings for your project somewhere if you're using Visual Studio.

For example with CMake, you'd invoke `cmake` with the command line argument `‑DNANODBC_ODBC_VERSION=0x0351` which would change the invocation for building the nanodbc translation unit from something like this:

``` shell
c++ -Wall -Werror -std=c++14 \
    `odbc_config --cflags` \
    -o /tmp/nanodbc.cpp.o \
    -c ~/source/nanodbc/src/nanodbc.cpp
```

to something like this:

``` shell
c++ -DNANODBC_ODBC_VERSION=0x0351 \
    -Wall -Werror -std=c++14 \
    `odbc_config --cflags` \
    -o /tmp/nanodbc.cpp.o \
    -c ~/source/nanodbc/src/nanodbc.cpp
```

(I actually noticed this wasn't working with CMake because I forgot to add the `add_definitions` line in the there but I just fixed that so it will actually work now :O oops...)

**Comment by ThermoX360** [comment]
Note that I had the same error running on Win7. Setting a preprocessor definition of NANODBC_ODBC_VERSION=SQL_OV_ODBC3 didn't work either. What did end up working for me was to set the following preprocessor definition :
NANODBC_DISABLE_ASYNC=1

**Comment by mloskot** [comment]
Yes, and the https://github.com/nanodbc/nanodbc/issues/89#issuecomment-358245213 gives hint why `SQL_OV_ODBC3` does not help here.
